//! Local `<img>` asset existence validation.

use super::helpers::{is_local_ref, start_line};
use crate::render::{Block, Severity, Warning};
use std::path::Path;

/// Unique local `src="..."` values from `<img>` tags only. Restricted to images on
/// purpose: `<audio>`/`<video>`/`<source>` refs are frequently generated by code
/// execution or are streamed/unvendored heavy media, which a static (no-execution) check
/// cannot resolve — checking them would false-flag. Links (`href=`) are out of scope.
///
/// Read through [`crate::render::tags`], the same walker the build's asset copier uses, so
/// the gate and the build agree about what an image reference is. This was a hand-rolled
/// scan until 2026-08-26 and disagreed three ways, each of them reproduced: it ended the tag
/// at the first `>`, so `<img alt="width > height" src="missing.png">` reported nothing; it
/// read only the double-quoted form, so `<img src='missing.png'>` reported nothing; and it
/// had no notion of tag-versus-text, so the `<img src="${e}">` fragments inside the inlined
/// mermaid and Plot bundles were read as broken images and `build --check-only` exited 1 on
/// a page whose only sin was carrying a hand-written `<script>`.
fn local_img_refs(html: &str) -> Vec<&str> {
    let mut out: Vec<&str> = Vec::new();
    for tag in crate::render::tags(html) {
        if !tag.name.eq_ignore_ascii_case("img") {
            continue;
        }
        let Some(val) = crate::render::attr_value(&tag, "src") else {
            continue;
        };
        if is_local_ref(val) && !out.contains(&val) {
            out.push(val);
        }
    }
    out
}

/// Local `<img src>` references (`![](img.png)`, raw `<img>`) whose target file does not
/// exist under the doc base dir — a broken image that ships silently today. Absolute
/// (`/...`) and external refs are out of scope; audio/video are skipped (see
/// [`local_img_refs`]: a static check cannot resolve generated/streamed media).
pub fn validate_local_assets(blocks: &[Block], base: &Path) -> Vec<Warning> {
    let mut out = Vec::new();
    for b in blocks {
        let line = start_line(&b.sourcepos);
        for val in local_img_refs(&b.html) {
            let path = &val[..val.find(['?', '#']).unwrap_or(val.len())];
            if path.is_empty() || path.starts_with('/') || base.join(path).is_file() {
                continue;
            }
            let w = Warning::new(format!(
                "local asset not found: `{path}` (no such file under the document directory)"
            ))
            .severity(Severity::Error);
            out.push(match line {
                Some(l) => w.at(b.source_file.clone(), l),
                None => w,
            });
        }
    }
    out
}
