//! Local `<img>` asset existence validation.

use super::helpers::{is_local_ref, start_line};
use crate::render::{Block, Severity, Warning};
use std::path::Path;

/// Unique local `src="..."` values from `<img>` tags only. Restricted to images on
/// purpose: `<audio>`/`<video>`/`<source>` refs are frequently generated by code
/// execution or are streamed/unvendored heavy media, which a static (no-execution) check
/// cannot resolve — checking them would false-flag. Links (`href=`) are out of scope.
///
/// Read through [`crate::render::tags`], the same walker the build's asset copier uses, so
/// the gate and the build agree about what an image reference is. This was a hand-rolled
/// scan until 2026-08-26 and disagreed three ways, each of them reproduced: it ended the tag
/// at the first `>`, so `<img alt="width > height" src="missing.png">` reported nothing; it
/// read only the double-quoted form, so `<img src='missing.png'>` reported nothing; and it
/// had no notion of tag-versus-text, so the `<img src="${e}">` fragments inside the inlined
/// mermaid and Plot bundles were read as broken images and `build --check-only` exited 1 on
/// a page whose only sin was carrying a hand-written `<script>`.
fn local_img_refs(html: &str) -> Vec<&str> {
    let mut out: Vec<&str> = Vec::new();
    for tag in crate::render::tags(html) {
        if !tag.name.eq_ignore_ascii_case("img") {
            continue;
        }
        let Some(val) = crate::render::attr_value(&tag, "src") else {
            continue;
        };
        if is_local_ref(val) && !out.contains(&val) {
            out.push(val);
        }
    }
    out
}

/// Local `<img src>` references (`![](img.png)`, raw `<img>`) that the published page will
/// not have: a missing file, or one the build cannot publish. Absolute (`/...`) and
/// external refs are out of scope; audio/video are skipped (see [`local_img_refs`]: a
/// static check cannot resolve generated/streamed media).
///
/// "Can be published" is the build's own rule, [`crate::includes::publishable`], judged
/// against the project the page is published from (its nearest `_site.yml`, else its own
/// directory: the root the site build copies from and the preview serves). The gate
/// accepted any file that merely existed until the 2026-09-24 audit, so `../outside.png`,
/// an image symlinked out of the checkout and one in a dot-folder passed `--strict` and
/// shipped broken. An image a page references in an `_images/` folder is published.
pub fn validate_local_assets(blocks: &[Block], base: &Path) -> Vec<Warning> {
    use crate::includes::{Reach, Unpublishable, publishable};
    let root = crate::includes::single_doc_root(base);
    let mut out = Vec::new();
    for b in blocks {
        let line = start_line(&b.sourcepos);
        for val in local_img_refs(&b.html) {
            // Resolved through the shared step (`render::asset_fs_path`): query/fragment
            // stripped, `%XX` decoded — the same answer the dev server and the build's
            // asset copier give, so `![x](my%20image.png)` beside a real `my image.png`
            // (the spelling VS Code drag-inserts) is not reported missing while the
            // preview serves it.
            let path = crate::render::asset_fs_path(val);
            if path.is_empty() || path.starts_with('/') {
                continue;
            }
            let message = match publishable(&root, base, Path::new(&path), Reach::Referenced) {
                Ok(below) if root.join(&below).is_file() => continue,
                Ok(_) => format!(
                    "local asset not found: `{path}` (no such file under the document directory)"
                ),
                Err(Unpublishable::Outside) => format!(
                    "local asset outside the project: `{path}` is not under {}, so the build \
                     does not publish it",
                    if root.join("_site.yml").is_file() {
                        "the folder holding `_site.yml`"
                    } else {
                        "the document's own folder"
                    }
                ),
                Err(Unpublishable::OutsideRepo) => format!(
                    "local asset outside the repository: `{path}` is a symlink out of the \
                     checkout, so the build does not publish it"
                ),
                Err(Unpublishable::Private) => format!(
                    "local asset in a private path: `{path}` has a `.`-prefixed component, \
                     which the build never publishes"
                ),
            };
            let w = Warning::new(message).severity(Severity::Error);
            out.push(match line {
                Some(l) => w.at(b.source_file.clone(), l),
                None => w,
            });
        }
    }
    out
}
