//! Local `<img>` asset existence validation.

use super::helpers::{is_local_ref, start_line};
use crate::render::{Block, Severity, Warning};
use std::path::Path;

/// Unique local image URLs: an `<img>`'s `src` and every `srcset` candidate, and a
/// `<source>`'s `srcset` (the `<picture>` form: the dark-mode or high-density image).
/// Restricted to images on purpose: `<audio>`/`<video>` sources (a `<source src>`) are
/// frequently generated by code execution or are streamed/unvendored heavy media, which a
/// static (no-execution) check cannot resolve; checking them would false-flag. Links
/// (`href=`) are out of scope. Each value is read through [`crate::render::attr_urls`], the
/// one reading of a `srcset` the build's copiers use too.
///
/// Read through [`crate::render::tags`], the same walker the build's asset copier uses, so
/// the gate and the build agree about what an image reference is. This was a hand-rolled
/// scan until 2026-08-26 and disagreed three ways, each of them reproduced: it ended the tag
/// at the first `>`, so `<img alt="width > height" src="missing.png">` reported nothing; it
/// read only the double-quoted form, so `<img src='missing.png'>` reported nothing; and it
/// had no notion of tag-versus-text, so the `<img src="${e}">` fragments inside the inlined
/// mermaid and Plot bundles were read as broken images and `build --check-only` exited 1 on
/// a page whose only sin was carrying a hand-written `<script>`.
fn local_img_refs(html: &str) -> Vec<std::borrow::Cow<'_, str>> {
    let mut out: Vec<std::borrow::Cow<'_, str>> = Vec::new();
    for tag in crate::render::tags(html) {
        let img = tag.name.eq_ignore_ascii_case("img");
        if !img && !tag.name.eq_ignore_ascii_case("source") {
            continue;
        }
        for a in crate::render::attrs(&tag) {
            let read = a.name.eq_ignore_ascii_case("srcset")
                || (img && a.name.eq_ignore_ascii_case("src"));
            if !read {
                continue;
            }
            for val in crate::render::attr_urls(a.name, &a.value) {
                if is_local_ref(val) && !out.iter().any(|v| v == val) {
                    out.push(std::borrow::Cow::Owned(val.to_string()));
                }
            }
        }
    }
    out
}

/// Local image references (`![](img.png)`, raw `<img>`, a `srcset`) that the published
/// page will not have: a missing file, or one the build cannot publish. Absolute (`/...`)
/// and external refs are out of scope; audio/video are skipped (see [`local_img_refs`]: a
/// static check cannot resolve generated/streamed media).
///
/// "Can be published" is the build's own rule, [`crate::includes::publishable`], judged
/// against the project the page is published from (its nearest `_site.yml`, else its own
/// directory: the root the site build copies from and the preview serves). The gate
/// accepted any file that merely existed until the 2026-09-24 audit, so `../outside.png`,
/// an image symlinked out of the checkout and one in a dot-folder passed `--strict` and
/// shipped broken. An image a page references in an `_images/` folder is published.
pub fn validate_local_assets(blocks: &[Block], base: &Path) -> Vec<Warning> {
    let root = crate::includes::single_doc_root(base);
    let mut out = Vec::new();
    for b in blocks {
        let line = start_line(&b.sourcepos);
        for val in local_img_refs(&b.html) {
            // Resolved through the shared step (`render::asset_fs_path`): query/fragment
            // stripped, `%XX` decoded — the same answer the dev server and the build's
            // asset copier give, so `![x](my%20image.png)` beside a real `my image.png`
            // (the spelling VS Code drag-inserts) is not reported missing while the
            // preview serves it.
            let path = crate::render::asset_fs_path(&val);
            if path.is_empty() || path.starts_with('/') {
                continue;
            }
            let Some(message) = unpublished(&root, base, &path, "local asset") else {
                continue;
            };
            let w = Warning::new(message).severity(Severity::Error);
            out.push(match line {
                Some(l) => w.at(b.source_file.clone(), l),
                None => w,
            });
        }
    }
    out
}

/// A page's front-matter `image:`, held to the same rule as a body image. It is the
/// `og:image` a shared link unfurls with and the listing card's thumbnail, and the page
/// never shows it itself, so a typo is a defect the author cannot see: it published an
/// `og:image` that 404s under a clean `--strict`. Resolved the way discovery resolves it:
/// against the page's directory, or from the project root for a root-absolute `/x.png`. An
/// external URL is not ours to check. Located at the `image:` line.
pub fn validate_front_matter_image(src: &str, base: &Path) -> Vec<Warning> {
    let Some(block) = crate::frontmatter::front_matter_block(src) else {
        return Vec::new();
    };
    let Ok(value) = serde_yaml::from_str::<serde_yaml::Value>(block) else {
        return Vec::new();
    };
    let Some(image) = crate::site::scalar(value.get("image")) else {
        return Vec::new();
    };
    let image = image.trim();
    if !is_local_ref(image) {
        return Vec::new();
    }
    let root = crate::includes::single_doc_root(base);
    let path = crate::render::asset_fs_path(image);
    let (from, rel) = match path.strip_prefix('/') {
        Some(rooted) => (root.as_path(), rooted),
        None => (base, path.as_str()),
    };
    let Some(message) = unpublished(&root, from, rel, "front-matter `image:`") else {
        return Vec::new();
    };
    let w = Warning::new(message).severity(Severity::Error);
    vec![match crate::frontmatter::block_key_line(block, "image") {
        Some(l) => w.at(None, l),
        None => w,
    }]
}

/// Why the file `path` (decoded, relative to `base`) will not be in the published output,
/// or `None` when it will: the one message set for every image check, spoken as `what`.
fn unpublished(root: &Path, base: &Path, path: &str, what: &str) -> Option<String> {
    use crate::includes::{Reach, Unpublishable, publishable};
    Some(
        match publishable(root, base, Path::new(path), Reach::Referenced) {
            Ok(below) => {
                let file = root.join(&below);
                crate::reads::probe(&file);
                if file.is_file() {
                    return None;
                }
                format!("{what} not found: `{path}` (no such file under the document directory)")
            }
            Err(Unpublishable::Outside) => format!(
                "{what} outside the project: `{path}` is not under {}, so the build does not \
                 publish it",
                if root.join("_site.yml").is_file() {
                    "the folder holding `_site.yml`"
                } else {
                    "the document's own folder"
                }
            ),
            Err(Unpublishable::OutsideRepo) => format!(
                "{what} outside the repository: `{path}` is a symlink out of the checkout, so \
                 the build does not publish it"
            ),
            Err(Unpublishable::Private) => format!(
                "{what} in a private path: `{path}` has a `.`-prefixed component, which the \
                 build never publishes"
            ),
        },
    )
}
