# Website design audit — backlog (2026-07-11)

Full, grindable findings from the 2026-07-11 multi-perspective audit of the **personal blog**
(`corpus/tech-blog/`, andreasbogossian.com — the priority) and the **marketing site** (`site/`,
taliesin.dev). Companion to [backlog.md](backlog.md); rendered report artifact:
https://claude.ai/code/artifact/bb4b030a-7724-49c8-98f5-95d7e5b1d5e4

## Why this exists

The blog's structure was **copied wholesale from Quarto and never independently evaluated**. Goals,
in priority order: (1) the blog is the author's forward-facing brand ("who I really am"); (2)
re-derive every Quarto decision from first principles; (3) make it his own / more native-Taliesin
(the marketing site is the reference); (4) promote recurring fixes into Taliesin's **defaults** so
every site benefits ("perfect the default"). No suggestion too small or too big.

## How this was produced

132 screenshots (3 viewports × 2 themes, both sites) + Lighthouse + a 10-perspective agent workflow
→ adversarial verification of every finding. **99 findings** (1 P0, 25 P1, 41 P2, 18 P3, 14 keep;
49 Quarto-inherited; 33 framework-default). 63 confirmed, 36 downgraded/caveated, 0 survived as false.

## How to use this file

Grind it. Each `- [ ]` is an item; check it `- [x]` or delete it when landed. Tags per item:
**severity** `P0/P1/P2/P3` · **scope** `[content]` (edit the blog) / `[framework]` (Taliesin core) /
`[content+framework]` · `Q` = Quarto-inherited · **effort** `S/M/L`. IDs (`` `#id` ``) are stable for
cross-session reference. The **Suggested order** below is the fast path; the **Full findings by lens**
section is the complete record with evidence + fix for every item. **KEEP list** at the very bottom:
protect those, do not "fix" them.

## Verified facts to build on (do NOT re-derive)

- Both sites score Lighthouse **100** on a11y / best-practices / SEO. This work is about **identity,
  structure, and de-Quarto-ification**, not broken fundamentals.
- `custom.css` (352 lines) is **~95% dead**: it targets Quarto/Bootstrap selectors Taliesin never
  emits (`.quarto-*`, `#quarto-margin-sidebar`, `.nav-footer`, `#TOC.toc-inline`, `.back-to-top`,
  `.listing-category`, `--bs-primary`, `bootstrap-icons`). Live rules: only `.sr-only` and
  `@view-transition`. The `.katex-display>.katex` rule is redundant with (not worse than) base.css.
- **Landmine:** deleting `custom.css` un-hides the footer social labels, because base.css defines only
  `.tali-sr-only`, not `.sr-only`. Alias `.sr-only` (or switch the footer to native `{icon:}`) FIRST.
- Real muted-text contrast already meets AA in both themes (native `--tali-muted`; no opacity-muting).
- Offline-first verified: **0 external requests** across all 17 captured pages.
- The native chrome is `tali-*` (`tali-nav*`, `tali-card*`, `tali-listing*`, `tali-about-*`,
  `tali-foot-*`, `<main id=tali-main>`), not the Quarto classes `custom.css` targets.

## Do-NOT-touch invariants (a fix that breaks one is wrong)

Offline-first / zero-CDN · single editing surface (preview never writes to source) · HTML-only output
· minimal-config (a better default beats a new knob) · theme system (`--tali-*` vars only, no vendor
hex, never opacity-muted text). Working method per `backlog.md`: branch per change, spec if there's a
fork, TDD, verify (cargo + chrome-devtools), ff-merge locally, delete the item here.

## De-Quarto quick reference

| Inherited decision | What Taliesin does with it | Verdict | Better move |
|---|---|---|---|
| `about: {template: jolla}` home | One fixed centered-avatar layout; `jolla` is an inert CSS class (no per-template styling) | **REPLACE** | Native `hero:` block (eyebrow + headline + lead + actions) |
| `custom.css` (352 lines) | ~95% targets classes Taliesin never emits; overflow rules duplicate base.css | **DELETE** | Reduce to empty after the two framework enablers below |
| `theme.scss` (219 lines) | Taliesin compiles no SCSS; unreferenced; obsolete darkly/no-accent intent | **DELETE** | Express real type intent via `--tali-*` vars |
| `head:` 3 CDN preconnects | Open real DNS+TCP+TLS to jsdelivr / Google Fonts on every load; nothing fetched | **DELETE** | Nothing replaces them; fonts are bundled |
| `instantpage.js` + `speculationrules` + `@view-transition` | 3 overlapping nav-prefetch mechanisms; instant.page is a redundant subset | **THIN** | Keep one; delete the 11 KB instant.page module + file |
| Footer RSS → `/blog.xml` | Engine silently drops the link (no feed); icon vanishes | **FIX** | Remove item now; framework: auto-generate a feed |
| `{.btn .btn-outline-primary}` | Bootstrap class, no native rule; falls back to base `.btn` by accident | **FIX** | Use `{.btn}` |
| `ieee.csl` | `csl:` isn't a Taliesin config key; unused | **DELETE** | IEEE numbering, if wanted, is a native cite request |
| `page-layout: article` | No-op (only `full` does anything) | **DROP** | Remove it (it's the default) |
| Global `toc: true` → `toc: false` ×4 | Inverted default 4/6 pages opt out of | **FLIP** | Drop the global; long posts opt in |
| `page-layout: full` · `title-block-style: none` | Genuinely implemented, honored, tested | **KEEP** | Leave them |

## Suggested order (fast path)

**P0 — today:** `#cv-lists-quarto-omits-taliesin`.

**P1, blog content (an afternoon):** `#no-native-taliesin-hero-grammar` / `#home-is-not-a-landing`
(rewrite home with a `hero:` block) · `#duplicate-home-description` + `#site-description-vague`
(fix the social card) · `#dead-cdn-preconnects` + `#redundant-nav-prefetch-stack` +
`#theme-scss-orphan` + `#ieee-csl-orphan` + `#custom-css-delete-to-zero` (de-Quarto sweep) ·
`#supercollider-prose-defects` + `#broken-audio-404` · `#footer-icon-shorthand` (kills the sr-only
dependency) · `#category-taxonomy-too-granular` + `#grid-vs-list-default-for-a-reading-blog`.

**P1, framework defaults (every site benefits):** `#search-btn-label-in-name` (⌘K aria-hidden, one
line) · `#autoplay-video-no-pause` note → the lightbox-on-`<video>` a11y-tree bug · `#sr-only-class-landmine`
(alias `.sr-only`) · `#missing-sitemap-robots` · `#no-native-feed-rss-swallowed` (feed generation) ·
`#no-json-ld-structured-data` · `#site-build-inlines-shared-assets` + `#katex-full-fontset-inlined-per-page`
(externalize) · `#duplicate-generic-titles` (title suffix) · `#about-header-no-subtitle-slot` ·
`#posts-are-navigational-deadends` · `#multiple-h1-per-post` (heading demotion / lint).

**Then** work P2 → P3 by lens below. Protect the KEEP list.

---

## Full findings by lens

All 99, severity-sorted within each lens. `↓` marks a finding the verifier downgraded/caveated.


### Quarto-inheritance archaeology (flagship)  (2 P1 · 4 P2 · 2 P3 · 1 keep)

> The blog's chrome is a Quarto skin bolted onto a framework that already replaced it natively, so most of the inherited machinery is either inert or actively harmful. The single worst archaeology cluster is the head:/body-end nav stack: three dead CDN preconnects (which still open real DNS+TCP+TLS handshakes to Google Fonts/jsDelivr on every load, a phone-home that flatly contradicts Taliesin's offline-first/zero-CDN invariant), a speculationrules prerender script, and a bundled 11KB third-party instant.page module, all layered on top of Taliesin's OWN native hover-preview (hover.rs / hover-index.js). custom.css is ~80% dead Quarto/Bootstrap selectors that match zero live DOM; theme.scss and ieee.csl are unreferenced orphans (Taliesin compiles no SCSS and reads no csl: key). The footer's RSS link 404s because no feed is emitted. The flagship identity problem is the copied about: template: jolla landing, which produces the single most generic academic-Quarto look and whose template name is inert (base.css styles no per-template class), where the native marketing site opens with a confident hero: block that has real identity. The genuinely good inherited decisions are page-layout: and title-block-style: none, both of which Taliesin deliberately implemented and honors.

- [x] `#dead-nav-prefetch-stack` **Three overlapping Quarto nav/prefetch mechanisms layered over Taliesin's native hover-preview; the CDN preconnects phone home** — `P1` [content+framework] `M` `Q`
  - *Problem:* _site.yml head: injects 3 preconnects to cdn.jsdelivr.net, fonts.googleapis.com, fonts.gstatic.com (confirmed inlined at index.html:1727-1729) plus a speculationrules prerender script, and body-end injects a third-party 11KB instant.page module (index.html:2939, file copied to build). A preconnect is not inert: it initiates DNS+TCP+TLS to those hosts on every page load even though the site uses zero external assets, so the offline-bundled blog opens unused connections to Google and jsDelivr — a phone-home that directly contradicts the offline-first / zero-CDN invariant. Meanwhile Taliesin ALREADY ships native cross-page hover-preview (crates/core/src/site/hover.rs, hover-index.js + 12-link-preview.js, wired at mod.rs:454-463), so instant.page is redundant with the native prefetch AND competes with the speculationrules prerender. Three mechanisms doing one job, none of them Taliesin's.
  - *Fix:* Delete the entire head: block and the body-end: instantpage.js line from corpus/tech-blog/_site.yml, and delete corpus/tech-blog/instantpage.js. The preconnects have no target (fonts are bundled) and the prefetch is covered natively. Keep only the cross-document @view-transition (see custom-css finding). FRAMEWORK: the config loader should warn when head: contains a preconnect to a host the build never requests, so no future Taliesin site smuggles a phone-home hint past offline-first.

- [x] `#rss-footer-link-404` **Footer advertises an RSS feed at /blog.xml that the build never produces — it 404s on click** — `P1` [content+framework] `M` `Q` ↓
  - *Problem:* _site.yml:47-48 puts an RSS icon in the footer linking to /blog.xml, but the build output contains no blog.xml (ls confirms: 404.html, blog.html, cv.html, index.html, projects.html, publications.html, posts/, projects/, plus assets — no feed). Every reader who clicks the RSS icon on the career-facing personal site gets a 404. The RSS-icon-in-footer is a Quarto website idiom that shipped without the feed generation Quarto would have done.
  - *Fix:* Immediate (content-config): remove the RSS footer item from _site.yml:47-48 until a feed exists. Better (framework-default, 'perfect the default'): a Taliesin website that has a date-sorted listing: (blog.tmd already declares contents: posts, sort: date desc) should auto-emit an Atom/RSS feed at a predictable path and only THEN is a footer link honest. Emitting the feed by default beats adding a feed: knob.

- [x] `#custom-css-mostly-dead` **custom.css is ~80% dead Quarto/Bootstrap selectors; the ~5 live rules duplicate base.css or belong in it** — `P2` [content+framework] `M` `Q` ↓
  - *Problem:* custom.css (352 lines) is inlined (no <link>; grep for custom.css in index.html returns nothing, it is folded into the <style>). Dead selectors that match zero live DOM: .quarto-grid-item, .mobile-category-filter/.quarto-listing-category/.quarto-category-count, #quarto-margin-sidebar, #quarto-content, #TOC.toc-inline (all of lines 133-289), .back-to-top (291-330), .nav-footer* (109-131), .listing-category/.listing-date (99-107, 202-210), --bs-primary (184/208/209), and the bootstrap-icons @font-face (23-27, no bootstrap icons are used, the footer uses inline SVG). Taliesin emits tali-nav*/tali-card*/tali-listing*/tali-foot-* instead, so every 'contrast fix' and the entire TOC/back-to-top/category-chip block is inert. The only live rules are .sr-only (used by the footer SVG labels), @view-transition, and the KaTeX/pre/table/img overflow rules (32-95) — but base.css almost certainly already handles pre/table/img/KaTeX overflow.
  - *Fix:* Cut custom.css down to the handful of live rules after diffing each against base.css; realistically only @view-transition and .sr-only survive as blog-specific. FRAMEWORK: fold the KaTeX .katex-display / pre / table / img horizontal-overflow rules and .sr-only into base.css so NO Taliesin site needs a custom.css to be mobile-safe or to hide screen-reader labels — then this file can be deleted entirely. Verify the small-screen font tweaks (333-352, targeting .page-layout-article which IS a native class per index.html:1721) against base.css's existing responsive rules before keeping them.

- [x] `#theme-scss-orphan` **theme.scss is an unreferenced darkly/SCSS orphan encoding a 'no accent' intent that contradicts the current native accent** — `P2` [content] `S` `Q`
  - *Problem:* corpus/tech-blog/theme.scss (219 lines) is not referenced by _site.yml or any .tmd (grep for theme.scss/theme: finds nothing), and Taliesin compiles no SCSS at all. Its header comment ('Loaded via: theme: [darkly, theme.scss]') is pure Quarto. It also hardcodes darkly's navy $primary:#375a7f and $link-color:#6b9ec8 and declares a design intent ('no accent color, all chrome is tonal') that is now obsolete: the live pages use base.css's native iron-gall --tali-accent #3a4673 (OKLCH H271). A future reader could mistake this file for the active theme.
  - *Fix:* Delete corpus/tech-blog/theme.scss. If any of its type choices are still wanted (Inter / JetBrains Mono, 1.75 line-height), they are already the native defaults or belong as reader-facing CSS-variable overrides, not SCSS.
  - *Landed 2026-07-11 (branch `deq-orphan-cleanup`):* deleted (also covers the duplicate `#theme-scss-orphan-delete` below). Minor cause nuance: `render/theme.rs:26-28` does *resolve* a `.scss` path in a `theme:` key (and flags it if unreadable), so "compiles no SCSS at all" is imprecise; but tech-blog sets no `theme:` key, so the file was genuinely unreferenced, and it was the only `.scss` in the corpus. `cargo test -p taliesin-core` green.

- [x] `#jolla-about-generic-identity` **The home page is Quarto's about: template: jolla — the most generic academic look, and the template name is inert** — `P2` [content+framework] `M` `Q` ↓
  - *Problem:* index.tmd:3-6 uses about: {template: jolla, image, image-alt}. Taliesin honors it (renders header.tali-about.tali-about-jolla at index.html:1757) but the template NAME is cosmetic-only: base.css and site.css define NO per-template rules (grep for tali-about-jolla/trestles/solana finds nothing), so 'jolla' vs any other value renders identically — Taliesin has exactly one about layout. More importantly, the result (centered circular avatar + name + hairline + one-line bio + a 2-card grid, laptop__dark.png) is the single most recognizable Quarto-academic template on the web and reads as a default, not as a personal brand. The native marketing site (site/index.tmd:5-12) opens instead with a hero: block (eyebrow 'MARKDOWN IN · LIVE HTML OUT', bold headline, lead, primary+secondary actions, site/index laptop__dark.png) that has genuine identity. The priority page of Andreas's brand is wearing the most template-y face available.
  - *Fix:* Replace the about: jolla block in index.tmd with a native hero: block (eyebrow/headline/lead/actions), the same primitive the marketing site uses, so the home page states who he is (ML + statistics + production software at Aalto) in a confident headline rather than a photo-and-name card. Keep the photo as a smaller element beside the hero if wanted. FRAMEWORK: either delete the inert tali-about-<template> class so the config surface doesn't imply variants that don't exist, or give jolla/trestles/solana real distinct layouts — but prefer the former (perfect one about layout) unless the corpus actually needs variety.

- [ ] `#global-toc-true-then-opt-out` **Site-wide toc: true is inverted from usage — 3 of 6 pages immediately set toc: false** — `P2` [content+framework] `S` `Q`
  - *Problem:* _site.yml:9 sets toc: true globally (Quarto's default), then index.tmd:8, publications.tmd:6, and cv.tmd:6 each override with toc: false. A default that half the pages must opt out of is the wrong default. A TOC only makes sense on the long-form posts; the about home, publications list, and CV are not it. The scattered toc: false lines are the fingerprint of an inherited default fighting the content.
  - *Fix:* Remove the global toc: true from _site.yml and let the long-form post pages opt in with toc: true (or rely on Taliesin auto-showing a TOC only when a page has enough headings). Then the three toc: false overrides disappear. FRAMEWORK: consider making a website's default 'TOC only on content pages with N+ headings', so no site needs a global toc flag plus per-page opt-outs.

- [x] `#ieee-csl-orphan` **ieee.csl is orphaned; csl: is not even a Taliesin config key** — `P3` [content] `S` `Q` ↓
  - *Problem:* corpus/tech-blog/ieee.csl is copied into the build but referenced by nothing: no csl: appears in _site.yml or any page/post (posts declare only bibliography: references.bib, e.g. posts/pca-geometry/index.tmd:10). The config loader reads no 'csl' key at all (crates/core/src/site/config lists title/description/url/favicon/image/output/toc/css/head/body-start/body-end/nav/footer/mounts/publish/chapters/author). Taliesin formats citations with its own native cite module, so a CSL style file is Quarto-only residue that does nothing.
  - *Fix:* Delete corpus/tech-blog/ieee.csl. If Andreas specifically wants IEEE-numeric citation style rather than Taliesin's default, that is a native feature request against the cite module, not a dropped-in .csl file — surface it as such rather than pretending the file is wired.
  - *Landed 2026-07-11 (branch `deq-orphan-cleanup`):* deleted. **Correction to the stated cause:** `csl:` **is** a recognized front-matter key (`includes.rs:171-188`, the resource-watch list), which the docs (`frontmatter.tmd:300`) already describe as "recognized but NOT honored". So it is unhonored, not unknown: the file's *content* is never parsed (IEEE author formatting is hardcoded natively in `cite/author.rs`), and no tech-blog page sets `csl:`, so the file was genuinely dead weight. `corpus/bayesian-website/ieee.csl` (which *does* set `csl: ieee.csl`) is a separate copy in a separate project and was left untouched. `cargo test -p taliesin-core` green.

- [x] `#btn-outline-primary-bootstrapism` **'View all posts' button uses the Bootstrap class .btn-outline-primary, not the native button convention** — `P3` [content] `S` `Q` ↓
  - *Problem:* index.tmd:28 writes [View all posts →](blog.tmd){.btn .btn-outline-primary}. .btn is styled natively (base.css a.btn) but .btn-outline-primary is a Bootstrap/Quarto class name with no native rule — its intended outline styling used to come from the now-orphaned theme.scss:149. On the live page it falls back to the base a.btn look (laptop__dark.png shows a plain outlined pill), so it works by accident, not by design, and carries a dead Bootstrap vocabulary word into otherwise-native content.
  - *Fix:* Drop .btn-outline-primary and use whatever native button variant the marketing hero uses for its secondary action ('Explore the features'), so blog and marketing buttons share one vocabulary. If Taliesin has no explicit outline-variant class, {.btn} alone already renders correctly — remove the Bootstrap-ism.

- [KEEP] `#keep-page-layout-and-title-block-style` **KEEP: page-layout: and title-block-style: none are Quarto idioms Taliesin deliberately implemented and honors** — `keep` [content] `S` `Q` ↓
  - *Problem:* Two Quarto-inherited frontmatter keys earn their place because Taliesin natively implements them (not accidental): page-layout: full widens the card indexes and page-layout: article gives the reading measure (base.css .page-layout-article .content, index.html:1721), and title-block-style: none genuinely suppresses the visible title header while keeping title metadata for <title>/OpenGraph/nav (crates/core/src/render/fm_extract.rs:33, render/mod.rs:206, with a dedicated test). These are real, tested behaviors, so they are safe to keep as-is.
  - *Fix:* Keep both keys. One small content follow-up, not a framework issue: publications.tmd combines title-block-style: none with no other heading, so the page renders with NO visible H1 at all (body starts at '## Theses', confirmed publications.html has no tali-title-block in the body). Decide if that bare look is intended; if not, drop title-block-style: none there so 'Publications' shows as the page title.


### Visual design, typography & color  (1 P1 · 3 P2 · 4 P3 · 1 keep)

> The blog and the marketing site sit on one shared foundation (base.css: serif body `1.125rem/1.7 ui-serif,Georgia`, sans headings, a single iron-gall indigo accent) — a genuinely distinctive, editorial pairing that is native Taliesin, not Quarto residue, and worth keeping. But the blog does not yet convert that foundation into a personal identity. Its home is the generic centered-avatar academic template; the one owned accent is almost entirely dormant (the page reads near-monochrome, and the only saturated color is an accidental red halo behind the avatar); and the intended custom face (Inter, per the dead theme.scss + dead Google-Fonts preconnects) never loads, so the whole "voice" of the site is whatever system serif the reader's OS happens to ship. Two real typographic defects compound this: listing/about lead paragraphs are set at the 62rem chrome width (~100ch, not the 46rem reading measure), and dark-themed figure thumbnails punch heavy black rectangles into the light-mode listing. The marketing site, by contrast, shows what confident Taliesin identity looks like (eyebrow + large tight display hero, filled accent buttons); the blog should borrow that confidence while staying editorial.

- [ ] `#text-face-is-system-dependent-not-owned` **The blog's typographic voice is an unbundled system serif; the intended custom face (Inter) is dead infrastructure** — `P1` [framework] `L` `Q`
  - *Problem:* The serif body resolves to `ui-serif, Georgia, "Times New Roman"` — all SYSTEM fonts. So the blog renders in Georgia on Win/mac and in some unrelated ui-serif on Linux: the 'voice' of a personal brand changes machine to machine and is never actually owned. Meanwhile the ONLY font infrastructure the blog ships is dead: theme.scss (orphaned, F2) specified Inter, and _site.yml head: injects three preconnects to fonts.googleapis.com / fonts.gstatic.com / cdn.jsdelivr.net (F3) that load nothing. KaTeX fonts ARE bundled offline, proving the pipeline exists — the text face is simply the one thing left to chance. For goal 3 ('make it his own / owned identity'), a rented-then-forgotten system serif is the opposite of owned.
  - *Fix:* Bundle one owned text trio into base.css as @font-face (woff2, subsetted, offline per zero-CDN): a distinctive text serif for --tali-font-body, a clean grotesque for --tali-font-head, keeping ui-mono. This makes EVERY Taliesin site render its identity identically offline. Then delete the three dead preconnects from tech-blog/_site.yml head: (F3) and delete theme.scss (F2). This is the highest-leverage move to convert the shared foundation into a memorable, consistent brand.

- [x] `#blog-home-generic-avatar-template` **Blog home is the generic centered-avatar academic template, not a confident personal opener** — `P2` [content+framework] `M` `Q` ↓
  - *Problem:* The home page (about: template: jolla, F7/F10 — a Quarto value Taliesin ignores) is a vertically-stacked centered avatar → centered name → one-sentence bio → hairline → two cards. It is indistinguishable from thousands of Quarto/Hugo academic about-pages and carries zero of the brand set up by the type system. Compare the marketing site's home (site/index): a mono eyebrow 'MARKDOWN IN · LIVE HTML OUT', a large tight-tracked display headline, a subhead, then filled+outline accent CTAs — that is what confident Taliesin identity reads like. The blog's first impression, the thing recruiters/peers see first (goal 1), is the weakest-designed page on the site.
  - *Fix:* Reauthor corpus/tech-blog/index.tmd to open with a real identity gesture instead of the jolla stack: a left-aligned display headline in --tali-font-head (e.g. a one-line thesis about what he works on), a short serif standfirst, and the LinkedIn/GitHub/CV links as accent chips — mirroring the marketing hero's structure (.hero pattern already exists in base.css:309). Keep the avatar but make it a supporting element, not the centerpiece. If a left-aligned hero for a person is a recurring need, add a native about layout variant to the site engine rather than leaning on the ignored 'jolla' name.

- [x] `#listing-lead-runs-at-chrome-width` **Listing/about lead paragraphs run to ~100ch because they use the 62rem chrome width, not the 46rem reading measure** — `P2` [framework] `M` ↓
  - *Problem:* On blog.tmd the intro sentence 'I write about concepts I'm working to understand…' spans the full grid container (left edge ~256px to ~1180px at 1440w ≈ the 62rem --tali-chrome-maxw), giving a single serif line of ~95-100ch — far past the ~66-75ch comfortable maximum, and roughly double the 46rem (~78ch) reading measure that body prose gets on a post. Long serif lines at that measure are genuinely hard to track back to the next line. Any prose an author writes above a listing grid inherits the wide layout container instead of the reading column.
  - *Fix:* In the site engine / site.css, constrain free prose blocks on listing and about pages to --tali-maxw (the reading measure) even when the page container is chrome-width for the card grid: wrap author markdown in a max-width: var(--tali-maxw) block while letting the grid itself span --tali-chrome-maxw. Grid width and reading measure are already separated as tokens (base.css:38-42); this just applies that separation to listing intros.

- [x] `#accent-dormant-near-monochrome` **The one owned iron-gall accent is nearly dormant on the blog — it reads as a plain grayscale template** — `P2` [content+framework] `M`
  - *Problem:* The whole point of the theme system is ONE owned indigo (OKLCH H271, base.css:2-9). On the blog it barely appears: the 'All' filter chip and the 'View all posts →' button outline are essentially the only accented pixels; post titles, dates, card titles, tag pills and hover states are all neutral gray. The result is a near-monochrome page that reads as a default doc theme rather than a site with a color identity — the exact 'generic-template look' goal 3 calls a failure. The marketing site, on the same token, uses the accent as a filled button color and active-nav marker, so it feels owned.
  - *Fix:* Deploy the accent as a deliberate, restrained signature: tint card-title hover and the post H1 link to --tali-link, use --tali-accent for the active nav item underline and the post date/kicker, and give tag pills an accent-tinted hover (color-mix with --tali-accent). Keep it ink-like, not button-like (the token was chosen to read as ink). This is mostly a framework-default win (site.css card/nav/tag rules) so every Taliesin site gains a visible identity color out of the box.

- [x] `#avatar-red-halo-clashes` **The avatar's red backdrop is the only saturated color on the home page and fights the indigo accent** — `P3` [content] `S` ↓
  - *Problem:* The circular avatar crop on the home page carries a strong dark-red background (the photo's environment). On a page whose owned accent is a cool iron-gall indigo, this warm red is the single most saturated element and it is accidental, not designed — it pulls the eye to a color that appears nowhere else in the system and undercuts the deliberate palette. It's especially prominent because the rest of the home is near-monochrome (previous finding).
  - *Fix:* Either swap in a portrait with a neutral/desaturated background, or neutralize it in-crop (subtle vignette / grayscale-toward-ink treatment), or add a solid ring in --tali-border-strong plus a small inner shadow so the red never touches the page. Content-level fix on corpus/tech-blog/index.tmd's about image; no framework change needed.

- [x] `#dark-thumbnails-punch-holes-in-light` (no change needed: native `.tali-card` already frames the image with border + radius + overflow, so a dark thumbnail reads as a framed figure; the audit saw the old Quarto listing) **Dark-themed figure thumbnails read as heavy black rectangles in the light-mode listing** — `P3` [content+framework] `M` ↓
  - *Problem:* Every post cover is a dark-background plot (WebGL/matplotlib on near-black). On the light-mode blog listing (white page, serif text) these become large solid black blocks with no frame, dominating the layout and creating a jarring light/dark imbalance — the cards look like holes cut in the page. In dark mode they integrate fine, so the listing is visually tuned for dark only. Uneven card heights (masonry) and a couple of two-line card titles ('PCA: the shape / hidden in your data') add minor raggedness.
  - *Fix:* Framework: give listing card images a subtle inset frame in light mode (1px --tali-border + small inner radius/shadow) so a dark thumbnail reads as a framed figure, not a void; consider equal-height card image aspect-ratio boxes in site.css to calm the ragged grid. Content: where practical, generate post covers with a theme-neutral or light-friendly background so they don't fight light mode.

- [ ] `#body-measure-slightly-wide-for-serif` **Post body measure (46rem ≈ 78ch at 18px serif) is a touch wide; tighten toward 66-70ch** — `P3` [framework] `S` ↓
  - *Problem:* --tali-maxw is 46rem; at 1.125rem (18px) Georgia with ~1rem side padding the text column is ~44rem ≈ 76-80ch. The classic comfortable maximum for continuous serif reading is 60-72ch; 78ch is readable but slightly loose, and it compounds the listing-intro problem above. This is the correct place to be conservative since it affects long-form posts (the priority content).
  - *Fix:* Nudge --tali-maxw to ~40-42rem (≈ 68-72ch) in base.css so long-form serif prose lands in the ideal band; keep --tali-chrome-maxw (62rem) for nav/footer/listing grid unchanged. Low-risk, benefits every Taliesin doc. If 46rem is deliberate for math/figure breathing room, at least verify it against a real post's line-length rather than leaving it at the inherited value.

- [ ] `#cv-tables-spreadsheet-style` **CV data tables are full-boxed spreadsheet grids — a plain, un-designed note in an otherwise clean page** — `P3` [framework] `M` `Q`
  - *Problem:* The CV's Skills and Languages tables render as fully-bordered cells (every cell boxed), which reads like a spreadsheet dropped into an editorial page and is the least-crafted element on an otherwise tidy CV. It clashes tonally with the serif prose and clean section rules around it.
  - *Fix:* Framework: restyle default table chrome in base.css toward a rule-based look (horizontal hairlines only, a slightly heavier header rule, generous cell padding, --tali-muted column headers) instead of full box borders — the classic 'financial table' treatment reads as designed and matches the editorial serif. Benefits every Taliesin table (CV, publications, docs).

- [KEEP] `#serif-body-sans-head-pairing` **Serif body + sans headings is the native default and a genuinely distinctive editorial voice — keep it** — `keep` [framework] `S`
  - *Problem:* base.css sets --tali-font-body to a serif stack (1.125rem/1.7 ui-serif, Georgia, Times) and --tali-font-head to ui-sans-serif. On the blog this produces a readerly, editorial serif body under crisp sans headings/UI — a confident, non-generic pairing that is emphatically NOT the sans-everywhere Bootstrap/Quarto default. It is native Taliesin (marketing shares the exact same tokens), it reads well in both themes, and the 1.7 body leading + modular heading scale give good vertical rhythm. This is the single strongest identity asset the blog already owns; do not flatten it to all-sans.
  - *Fix:* Keep the serif-body / sans-head split as the framework default. The remaining work (findings below) is to make the serif an OWNED face rather than a system fallback, and to actually deploy the accent — not to change the pairing itself.


### Brand, identity & personal voice — "who I really am" (+ generative directions)  (1 P0 · 5 P1 · 2 P2 · 2 keep)

> The blog's first impression is an anonymous Quarto "jolla" template: a casual selfie, a centered name, a flat LinkedIn-grade one-liner, and a rule. It carries no point of view, no memorable tagline, and almost none of the confident, native-Taliesin voice that the marketing site radiates (mono eyebrow, display headline, iron-gall accent CTA). Ironically the strongest, most distinctive copy Andreas has written ("I write about concepts I'm working to understand"; "I build systems at the intersection of math and production-quality software") is buried on /blog and /cv, while the homepage, the page that matters most, gets the weakest line. The real brand asset already on the page is the pair of live, generated math figures used as post thumbnails; they signal ability better than any prose and should be leaned into hard. Two brand-damaging specifics: the tagline "Notes on challenging technical things" is generic and is never even rendered for a visitor, and the CV lists "Quarto" as a current tool while omitting Taliesin, the framework Andreas built to replace it. Below: fixes plus three concrete identity directions grounded in his content and Taliesin's design language.

- [x] `#cv-lists-quarto-omits-taliesin` **CV lists Quarto as a current tool and omits Taliesin, the opposite of his story** — `P0` [content] `S`
  - *Problem:* The CV Skills table 'Tools' row reads 'Git, Ubuntu, Quarto' (visible in cv/laptop__dark.png, Skills table bottom row). This is an active brand contradiction: Andreas's flagship project IS a from-scratch Quarto replacement (he 'has fully left Quarto'). A sharp recruiter or collaborator who clicks Projects/GitHub sees him building Taliesin to escape Quarto, then lists Quarto as a tool he uses, and does NOT list the substantial thing he actually built. The most impressive artifact he owns (a working document-compilation dev server, warm kernels, native slide engine) is invisible on his own CV, while the tool he abandoned is front-and-center.
  - *Fix:* In corpus/tech-blog/cv.tmd Skills table, replace 'Quarto' with 'Taliesin' (his own shipped tool) and consider a dedicated one-line project mention near the top of the CV, e.g. under the subtitle. If he wants to keep a document-authoring skill visible, 'Taliesin (author)' is a far stronger signal than 'Quarto (user)'. This is the single cheapest, highest-brand-leverage edit in the whole audit.

- [x] `#homepage-weakest-voice` **The homepage gets his blandest bio while his best voice sits on /blog and /cv** — `P1` [content] `S`
  - *Problem:* The homepage bio (index.tmd:21) is 'MSc student in ML, Data Science and AI at Aalto University. I write about machine learning, statistics, and algorithms.' It is factual, flat, and indistinguishable from ten thousand LinkedIn headlines: it states affiliation and topic but no point of view, no personality, no reason to keep reading. Meanwhile /blog opens with 'I write about concepts I'm working to understand, mostly machine learning, statistics, and algorithms' (blog.tmd:11) which is humble, specific and human, and /cv opens with 'I build systems at the intersection of math and production-quality software' (cv.tmd:12) which is crisp and confident. The strongest lines are on secondary pages; the priority page (first impression, goal #1) gets the weakest. A recruiter's 5-second takeaway right now is 'another ML masters student', not 'this person has taste and a way of thinking'.
  - *Fix:* Rewrite index.tmd:21 to carry a POV, borrowing the energy of the lines he already wrote. Concretely, something like: 'I write about the math and geometry underneath machine learning: concepts I'm working to understand, built up from first principles and running code.' Pull the CV's 'intersection of math and production-quality software' framing in too. Keep it 1-2 sentences. The bar is: a stranger should finish it knowing his angle (intuition/geometry/first-principles ML), not just his degree.

- [x] `#tagline-invisible-and-generic` **The tagline 'Notes on challenging technical things' is generic and never shown to a visitor** — `P1` [content+framework] `S` `Q`
  - *Problem:* _site.yml:5 sets description: 'Notes on challenging technical things'. Two problems. (1) It is vague filler: 'challenging technical things' says nothing about ML/stats/geometry and reads as a placeholder; compare the marketing site's sharp 'Markdown in / live HTML out' eyebrow. (2) It is invisible: the description feeds meta/SEO only; nothing on the rendered homepage displays it (index/laptop__dark.png shows name, rule, bio, Recent Posts, no tagline anywhere). So the one line meant to be the brand hook is both weak and hidden. The homepage has no eyebrow, no wordmark line, no motto, the visitor gets no compressed identity statement at all.
  - *Fix:* Rewrite the tagline to state the actual angle, drawn from his content (his PCA post subtitle 'the shape hidden in your data' is the tone to hit). Options: 'The math and geometry under machine learning', 'Machine learning, from the math up', 'ML and statistics, worked out from first principles'. Then SURFACE it: render it as an eyebrow/subtitle on the homepage (see about-header-no-subtitle-slot). Do not leave the brand line living only in a meta tag.

- [x] `#no-native-taliesin-hero-grammar` **Homepage reads as a generic template, not native-Taliesin: the confident hero grammar is unused** — `P1` [content+framework] `M` `Q`
  - *Problem:* Side by side, the two sites do not read as made by the same person with the same design language. The marketing site (site/index/laptop__dark.png) opens with a mono letter-spaced eyebrow 'MARKDOWN IN · LIVE HTML OUT', a big two-line display headline, a lead, and an iron-gall accent CTA, a distinctive, confident identity. The blog (index/laptop__dark.png) opens with the Quarto 'jolla' about template: round photo, centered name, one grey paragraph. It is competent but anonymous; nothing about it says 'Taliesin' or 'Andreas' specifically. The native hero primitive that gives the marketing site its identity ALREADY EXISTS (base.css:305-317: .hero, .hero-eyebrow mono caps, .hero-actions) and the blog simply doesn't use it, it inherited Quarto's about layout instead and never re-evaluated it (goal #2).
  - *Fix:* Give the blog homepage the native hero grammar. Two routes: (a) content-config today, keep the photo but add an eyebrow + headline line above/around the name; or (b) adopt `hero:` frontmatter for a headline+eyebrow+lead and place the photo as a smaller accent. Either way the homepage should get a mono eyebrow (his tagline) and a headline that is a statement, not just his name, matching the marketing site's confidence so both sites clearly share one design language. See identity-directions for three concrete looks.

- [x] `#about-header-no-subtitle-slot` **The about header has no subtitle/eyebrow slot, so the identity line floats below a rule as body text** — `P1` [content+framework] `M` `Q`
  - *Problem:* The native about header (site/mod.rs:1215-1216) emits only img + h1(name) + links, no subtitle. So on the homepage the identity line renders as a detached grey paragraph BELOW a horizontal rule (index/laptop__dark.png: name, then a full-width rule, then the bio in a separate block), reading as an afterthought disconnected from the name. Contrast the CV, which sets `subtitle: 'Machine Learning · Software'` (cv.tmd:3) and renders it tight under the name inside the title block (cv/laptop__dark.png), a clean identity treatment. The homepage, the priority page, has the WORSE treatment because the about template lacks the subtitle slot the ordinary title block has. This is exactly the marketing hero's .hero-eyebrow slot missing from the about layout.
  - *Fix:* Framework-default: extend the about layout (crates/core/src/site/mod.rs about-header emit + .tali-about-* in site.css:154-165) to honor a `subtitle:` (and/or an eyebrow) key, rendered as a mono/letter-spaced line directly under .tali-about-name, mirroring .hero-eyebrow (base.css:313) and the CV's subtitle. This is a better DEFAULT, not a new knob for its own sake: every Taliesin about page currently strands its one-line pitch as loose body text. Content-config in the meantime: Andreas can put the tagline as the first thing after the name rather than after the rule.

- [x] `#identity-directions` **Three concrete identity directions for the blog (name, type, color, layout, homepage)** — `P1` [content] `L`
  - *Problem:* The blog currently has no identity of its own, it is the residual shape of a Quarto template (goal #3: 'generic-template look is a failure'). It needs a deliberate, memorable direction that reads as HIM and as native-Taliesin. All three below build on primitives that already exist (.hero/.hero-eyebrow, iron-gall accent, article serif body) so none require abandoning Taliesin invariants (offline, no vendor hex, single editing surface, minimal config).
  - *Fix:* DIRECTION A - 'Marginalia' (the ink-notebook). Concept: the iron-gall accent is literally a historical manuscript ink; lean into it. Type: serif display headlines (the article body is already serif), mono eyebrow. Color: accent used as 'ink' for a hairline rule and the eyebrow. Layout: mono eyebrow ('ML · STATISTICS · ALGORITHMS'), a serif POV headline (not just his name), photo small and to the side, then the two live-figure post cards. Reads as him = a mathematician who writes carefully; native-Taliesin = uses the accent as intended + the mono eyebrow grammar of the marketing hero. DIRECTION B - 'Evidence' (the live lab). Concept: 'I don't tell you, I show you', mirror the marketing site's live 3D hero. Type: clean sans headline, mono eyebrow, generous space. Color: accent on the interactive element + dates. Layout: a full-width live {js} or figure hero (e.g. the Fourier epicycles from his own post, animating), headline + tagline beneath, cards below. Reads as him = production ML + interactive math; native-Taliesin = dogfoods the {js}/live-figure capability the framework is proudest of. (Respects offline-first: the figure must be self-contained/bundled, not CDN.) DIRECTION C - 'Index' (terminal/engineer). Concept: signal over decoration; no photo hero. Type: a typographic wordmark ('ANDREAS BOGOSSIAN' or 'ab' in mono), tight. Color: accent for dates + tags. Layout: wordmark + one-line tagline, then a dense reverse-chron index (mono dates, titles, tags), the listing IS the page. Reads as him = an engineer who values density and honesty; native-Taliesin = mono, minimal-config, listing-first. Recommend prototyping A or B first (they retain warmth + the strong figure cards) and reserve C as the confident-minimal alternative.

- [x] `#accent-absent-on-blog` **No signature color moment: the blog homepage is monochrome grey while the accent is the brand** — `P2` [content+framework] `M`
  - *Problem:* Taliesin's one owned brand color is the iron-gall accent (OKLCH H~271). On the blog homepage it appears essentially nowhere: the name, rule, bio and 'Recent Posts' are all neutral grey/white (index/laptop__dark.png and __light.png), and the accent surfaces only on the 'View all posts' button outline and link hovers. The marketing site by contrast commits to the accent on its primary CTA and headline treatment. A brand needs a repeatable color signature; right now the blog's identity color is invisible on its most-seen page, so the site reads as a default dark theme rather than 'his'.
  - *Fix:* Introduce one deliberate accent moment on the homepage: an accent-colored eyebrow or a short accent rule/underline under the name (replacing the flat full-width grey border), or accent the post dates/category chips in the listing. Keep it restrained (one moment, not everywhere) and via --tali-accent / --tali-link variables only, never hardcoded hex (theme invariant). This is partly framework-default: the listing card date/category could carry the accent by default so every Taliesin site gets a color signature.

- [x] `#profile-photo-casual` **The profile photo is a casual selfie, not a deliberate brand asset** — `P2` [content] `S`
  - *Problem:* The hero photo (index/*, cv) is a close, casually-lit selfie against a red couch/background. For a career-facing brand aimed at recruiters and collaborators (goal #1), the portrait is a taste signal, and a considered, evenly-lit portrait (or a distinctive non-photo mark) would read as more intentional. The current image is fine but reads 'phone selfie', slightly undercutting the 'production-quality software' positioning the CV claims. This is a judgment call, not a bug.
  - *Fix:* Optional: replace profile.webp with a deliberate portrait (neutral/considered background, consistent with the site's dark palette), or lean the other way and drop the photo entirely in favor of a typographic wordmark hero (see identity-directions C). If keeping a photo, ensure the crop and background feel chosen. Reader impact is real but modest; keep this below the copy/CV fixes.

- [KEEP] `#keep-live-figure-thumbnails` **KEEP + amplify: the live-generated math figures as post thumbnails are the real brand** — `keep` [content] `S`
  - *Problem:* The two Recent Posts cards use genuinely produced math visuals as thumbnails, the Fourier epicycle field and the 3D PCA scatter with labeled principal axes (index/laptop__dark.png). These are not stock images; they are outputs of his own posts, and they communicate 'this person can actually do the math and render it' in under a second, far more persuasively than the prose. This is the single strongest brand element on the page and it is good.
  - *Fix:* Keep, and make it a system, not an accident. Ensure every post ships a strong generated figure as its listing image so the homepage/blog grid is always a wall of real math visuals, that consistency IS the identity (ties to Direction B). Do not let any post fall back to a text-only card. Frame this as the blog's signature and design the homepage around showcasing it (larger cards, figure-forward).

- [KEEP] `#keep-blog-and-cv-voice` **KEEP: the /blog and /cv opening lines are the authentic voice, promote them** — `keep` [content] `S`
  - *Problem:* 'I write about concepts I'm working to understand' (blog.tmd:11) and 'I build systems at the intersection of math and production-quality software' (cv.tmd:12) are genuinely good: specific, humble-but-confident, distinctly his. The problem is only their placement (see homepage-weakest-voice); the writing itself is exactly the brand voice the site needs, and it should be validated and reused, not rewritten away.
  - *Fix:* Keep these lines and elevate them: make the 'concepts I'm working to understand' framing the through-line of the whole blog (it is a memorable, differentiated positioning, learning-in-public by a strong mathematician), and echo it on the homepage. Treat it as the canonical statement of who he is.


### Information architecture, navigation & listing UX  (2 P1 · 5 P2 · 3 P3 · 1 keep)

> The blog's IA is a wholesale Quarto academic-template copy (Home-as-about-card / Blog / Publications / Projects / CV) that was never re-derived for a career-facing personal brand. The homepage does the weakest possible job: a generic centered "jolla" about-card (avatar, name, one bio line, two recent posts) with no tagline, positioning, or narrative, which reads as a template next to the marketing site's confident hero+narrative landing at site/index.tmd. Two nav destinations are near-empty or duplicated: Publications is a single thesis rendered verbatim in both publications.tmd and cv.tmd, and cv.tmd additionally re-renders the entire Projects listing. The category system is decorative-only (card chips aren't links, there are no per-tag pages, and 11 categories over 7 posts mostly have a count of 1), and posts are dead-ends with no next/prev/related/back affordance beyond "← Blog". The listing card design and the honest "things I built to learn" framing are genuinely good and should stay; almost everything else in the IA earns a rethink, with the home-as-landing and post-cross-linking gaps being the highest-leverage framework-default fixes.

- [x] `#home-is-not-a-landing` **Homepage is a generic Quarto about-card, not a landing that shows who he is** — `P1` [content+framework] `M` `Q`
  - *Problem:* The #1 goal is 'showing who I really am' for recruiters/peers, but the homepage (index.tmd) is a centered 'jolla' about-card: avatar, the name 'Andreas Bogossian' repeated as an H1 (already the nav brand, top-left), a single duplicated bio line, then exactly 2 recent posts and a 'View all posts' button. There is no tagline/eyebrow, no positioning statement, no signal of depth or range, no path into Projects/CV/contact. Compared to the native Taliesin reference (site/index.tmd: eyebrow 'MARKDOWN IN · LIVE HTML OUT', a big two-line headline, a subhead, two CTAs, then a running narrative), the blog home reads as a low-signal template. Showing only 2 of 7 posts (max-items: 2) further starves the page.
  - *Fix:* Redesign the home as an actual landing: (1) drop the redundant name H1 (nav brand already carries it) and lead with a confident one-line positioning statement + a short 'what you'll find here' paragraph; (2) bump the recent-posts listing to 3 and add explicit routes into Projects and CV plus a contact/hire line, not just 'View all posts →'; (3) treat this as a chance to establish the personal identity the goals ask for (a signature accent moment, an eyebrow like the marketing site). In the framework, replace the honored-but-Quarto 'about: {template: jolla}' path (index.tmd:3-6) with a native Taliesin home/landing pattern so every site gets an opinionated default instead of the academic card.

- [ ] `#posts-are-navigational-deadends` **Post pages dead-end: no next/prev, no related, no categories shown, only '← Blog'** — `P1` [framework] `M`
  - *Problem:* A reader who lands on a post (e.g. PCA) can go up ('← Blog') or use the TOC, but there is no next/previous post, no 'related posts', no series linkage, and the post's own categories/tags are not even displayed on the post itself (they exist only on the listing card). Every post is a cul-de-sac, which caps time-on-site and cross-discovery, exactly the wrong outcome for a portfolio whose job is to make a recruiter read a second thing.
  - *Fix:* Add a post-footer navigation block as a framework default in the site engine / page assembly: show the post's categories (linking to the tag pages from the finding above), a prev/next pair (sorted by date), and optionally 2-3 related posts by shared category. Also surface categories at the top of the post title block. Keep '← Blog' as the up-link. This should live in crates/core/src/site + render/page.rs so every Taliesin blog gets it, not per-post frontmatter.

- [ ] `#publications-nav-slot-is-one-item-and-duplicated` **'Publications' is a top-level nav slot holding a single thesis, duplicated verbatim on the CV** — `P2` [content] `S` `Q` ↓
  - *Problem:* publications.tmd is just an H2 'Theses' plus a one-item include (_includes/publications.md, a single B.Sc. thesis). The rendered page is 90% empty whitespace below one entry. The exact same include is pulled into cv.tmd:44 under a 'Publications' section, so the identical content exists at two nav-reachable places. A near-empty top-level nav item signals thin content to the very recruiters this site targets, and the duplication is a maintenance trap.
  - *Fix:* Drop 'Publications' from the nav (nav.left in _site.yml:31-32) and keep the thesis only in its CV section; or, if it must stay standalone, retitle it 'Writing & Publications' and give it real weight (thesis + a curated list of the strongest posts). Keep the single source (_includes/publications.md) and include it in exactly one destination to kill the duplication.

- [ ] `#cv-re-renders-entire-projects-listing` **CV page re-renders the full Projects listing it just linked away to** — `P2` [content] `S` `Q` ↓
  - *Problem:* cv.tmd's Projects section says 'The full set lives on the Projects page' and links there (cv.tmd:48), then immediately renders a #cv-projects listing (type: default) of ALL four projects as cards at the bottom of the CV (cv.tmd:6-11,50-51). So the CV both delegates to and duplicates the Projects page, making an already-long single-page CV even longer and contradicting its own copy. The stacked default-type cards at the bottom also visually clash with the tight typographic CV above them.
  - *Fix:* Pick one: either delete the #cv-projects listing and keep just the sentence+link to Projects (leanest, matches the copy), or delete the sentence and keep a curated 2-3 item highlight listing (add max-items and a 'selected' filter). Do not do both. If keeping a listing, use a compact inline style, not full cards, so it reads as a CV section not a second Projects page.

- [ ] `#category-chips-not-linkable-no-tag-pages` **Category chips on cards are decorative; no shareable per-tag URLs or tag pages exist** — `P2` [framework] `L` `Q` ↓
  - *Problem:* The per-card category chips render as tali-card-cats with NO <a href> (confirmed: grep finds 8 tali-card-cats and zero <a...tali-card-cat> in blog.html), so a reader who clicks a tag like 'linear algebra' on a card gets nothing. The only category affordance is the in-page tali-cat-filter button row (data-cat JS filter) at the top of blog/projects. That means: no deep-linkable filtered view, no per-tag landing page, no way to share or bookmark 'all my probabilistic-ML posts', and clickable-looking chips that are inert. For a topic-driven technical blog, topic pages are a core findability mechanism.
  - *Fix:* Make categories real navigation in the site engine: (a) reflect the active filter in the URL (e.g. ?cat=linear-algebra) so filtered views are shareable/back-button-safe, and/or (b) emit a lightweight per-category listing page and make both the filter chips and the card chips <a> links to it. This is a framework-default gap in crates/core/src/site (listing/xref); fixing it there gives every Taliesin site linkable taxonomy without a per-site knob.

- [ ] `#category-taxonomy-too-granular` **11 blog categories over 7 posts, most with count 1 — the filter barely filters** — `P2` [content] `S` `Q`
  - *Problem:* The blog filter row shows All + 11 categories: algorithms 2, graph theory 1, hypothesis testing 1, information theory 1, linear algebra 1, machine learning 1, probabilistic ML 3, signal processing 1, statistics 1, variational inference 2. Seven of eleven have exactly one post, so clicking most chips just isolates a single card — the taxonomy is finer-grained than the corpus, which makes the filter feel busy and low-value and wraps to two rows even at laptop width.
  - *Fix:* Consolidate to ~4-6 durable topics (e.g. Statistics & inference, Machine learning, Algorithms, Signal & information theory) by editing the categories in each post's frontmatter; a coarser taxonomy makes the filter and the (proposed) tag pages meaningful. Content-config now; separately consider a framework default of hiding categories with count 1 or collapsing rare tags behind a 'more' affordance.

- [ ] `#no-explicit-contact-hire-affordance` **Career-facing site has no clear contact/hire path** — `P2` [content] `S`
  - *Problem:* For a site whose stated job is being read by recruiters and collaborators, the only ways to reach or connect are footer social icons (LinkedIn/GitHub, whose accessible labels also mismatch per F6) and three inline links on the CV. There is no email, no 'get in touch', no availability/hire signal anywhere in the primary IA. A recruiter who is convinced by a post has no obvious next action.
  - *Fix:* Add an explicit contact affordance: an email + 'open to X' line in the redesigned home landing and/or a short 'Contact' block at the foot of the CV, and consider a lightweight standing footer link. This is content-config for Andreas; the underlying framework default (a nav/footer that makes a contact link a first-class option) is already available via footer config, so no new knob is needed.

- [x] `#grid-vs-list-default-for-a-reading-blog` **3-column grid is the wrong default for a text-first blog; titles/descriptions get squeezed** — `P3` [content+framework] `M` `Q` ↓
  - *Landed 2026-07-11 (Session 4, local main):* the author picked a **reading-first list** (AskUserQuestion). Added a framework `type: list` listing layout: a stacked row (thumbnail beside date · title · full description · categories) that **keeps** the live-figure thumbnail the KEEP list `#keep-live-figure-thumbnails` protects, at a comfortable reading width (dropped `page-layout: full` from blog.tmd). Implementation: a `with_image` flag on `ListingSpec` (`grid`|`list` show the thumbnail; plain `default` stays text-only, so the CV's `type: default` projects tail is UNCHANGED, verified). Reuses the existing `.tali-listing-default` row CSS; no new CSS. Did NOT make `list` the blog's silent default (that would flip every `type: default` list, incl. the CV, to thumbnails) — an explicit named type is the minimal-config-honest choice. Pinned by `list_layout_shows_thumbnail_but_default_stays_text_only`; browser-verified at 390/900/1440 in both themes (mobile stacks to full-width cards). vocab + configuration.tmd updated.
  - *Problem:* The blog uses type: grid (blog.tmd:7). At laptop width the 3-up cards force titles to wrap mid-phrase ('PCA: the shape / hidden in your data', 'The Kruskal-Wallis test, / derived from first principles') and clamp descriptions, so the listing reads as thumbnails rather than an inviting index of writing. Grid suits Projects (screenshot-driven), but a deep-technical blog is text-first and benefits from a list with room for a real dek. The grid is a Quarto listing default carried over unquestioned.
  - *Fix:* Default the blog listing to a list/feed layout (date · title · one-to-two-line description · categories, optional small thumbnail) and reserve grid for visual collections like Projects. In Taliesin, make 'list' the default listing type for a blog-shaped page (perfect the default rather than requiring type: on every blog); keep grid available for project galleries. Cap the description dek so cards stay even.

- [ ] `#three-divergent-self-descriptions` **Three different bios/positioning statements across home, blog, and CV** — `P3` [content] `S` ↓
  - *Problem:* The site states who he is three different ways: home 'MSc student in ML, Data Science and AI at Aalto University. I write about machine learning, statistics, and algorithms.' (index.tmd:21); blog 'I write about concepts I'm working to understand, mostly machine learning, statistics, and algorithms.' (blog.tmd:12); CV 'M.Sc. student at Aalto University specialising in machine learning and mathematics. I build systems at the intersection of math and production-quality software.' (cv.tmd:13). None is clearly the canonical tagline, so the brand voice is diffuse and the strongest framing (the CV's 'math + production-quality software') is buried on the least-visited page.
  - *Fix:* Choose one canonical positioning line (the CV's is the strongest and most memorable) and use it as the home tagline, keep the blog intro as the distinct 'why I write' line, and let the CV bio be the formal expansion. Deliberate reuse, not three drafts.

- [ ] `#cv-as-single-page-with-projects-tail-mixes-registers` **CV-as-a-page is a reasonable choice, but its layout mixes formal CV with blog-style cards** — `P3` [content+framework] `M` `Q` ↓
  - *Problem:* Rendering the CV as a browsable page (rather than only a PDF) is a good, web-native decision and fits the HTML-only invariant. But the current page runs a long, dense, tightly-typeset CV (Education → Skills → Publications → Projects → Experience → Honors → Volunteering → Languages) and then abruptly appends four full blog-style project cards, so the page shifts register from 'formal CV' to 'listing' at the bottom (see finding cv-re-renders-entire-projects-listing). There's also no 'download PDF / print' affordance for the actual recruiter use-case of saving a CV.
  - *Fix:* Keep CV-as-a-page, but end it on a formal note (remove the card tail per the duplicate finding) and add a clear 'Download / Print CV' action; Taliesin builds HTML only, so this is a print-stylesheet + a print CTA (reader-local, allowed), not a PDF track. A tuned @media print in site.css is a good framework default for the CV/article layout.

- [KEEP] `#projects-listing-and-framing-are-good` **Projects listing (visual cards + honest 'things I built to learn' framing) should stay** — `keep` [content] `S`
  - *Problem:* Not a problem — a genuinely good decision worth protecting. The Projects page pairs a distinctive one-line intro ('Things I built to learn something. Each project page documents what it does, how it works, and what I took away from it.') with grid cards that each carry a strong custom thumbnail (waveform, activity-bot art, Bayesian forest plot, correlation heatmap), a date, a tight title, a one-line summary, and topic chips. The visuals read as real work, the framing is confident and personal, and the grid is the right layout here because the thumbnails carry information.
  - *Fix:* Keep this listing layout and framing as-is; use it as the template for what a Taliesin project/gallery listing should look like by default, and make sure the tag-page / linkable-category work (finding category-chips-not-linkable) does not regress its clean card look.


### Content, copywriting & editorial  (1 P1 · 6 P2 · 3 P3 · 1 keep)

> The blog's writing is a tale of two registers. Where Andreas writes in his own voice, the copy is genuinely good: the blog tagline ("concepts I'm working to understand"), the projects tagline ("Things I built to learn something"), and most post descriptions ("How mathematics hears which notes are hidden in a chord") are specific, confident, and human. But the top-of-funnel strings that carry the personal brand are the weakest: the site-wide description ("Notes on challenging technical things") is vague, the homepage hero is just his name repeated twice plus a dry topic list with none of the marketing site's eyebrow/headline/lead structure, and he tells three different self-descriptions across home/CV/blog. Metadata is thin: dates render in raw ISO ("2026-05-15"), there is no reading time, and categories vanish from the post header. There are also two real editorial defects: the CV lists "Quarto" (the tool he abandoned) instead of Taliesin (the tool he built), and a project page ships a typo plus a sentence truncated mid-word. The marketing site copy is the model to measure the blog against; the blog just hasn't been given the same intentional voice at the top.

- [x] `#supercollider-prose-defects` **supercollider-mcp opening paragraph has a typo and a sentence truncated mid-word** — `P1` [content] `S`
  - *Problem:* projects/supercollider-mcp/index.tmd:14 ships two visible editorial defects in the first paragraph a reader sees: (1) "but why now ask LLMs to then produce code" — "now" should be "not"; (2) the paragraph ends mid-word: "...so with SuperCollider, th" — the sentence is cut off and never completes. This is published on a project page a recruiter or collaborator may read, and a broken sentence in the opening line badly undercuts the "who I really am" brand. (This project also has the two 404ing audio demos noted in F5, compounding the impression the page is unfinished.)
  - *Fix:* Fix line 14: change "why now ask" to "why not ask", and complete the truncated sentence (it appears meant to introduce SuperCollider, which the next paragraph then does — likely just delete the dangling "so with SuperCollider, th" fragment or finish the thought). Proofread the rest of the paragraph while there ("th"→"the", tighten the double "but... but").

- [x] `#site-description-vague` **Site-wide description "Notes on challenging technical things" is vague and off-voice** — `P2` [content+framework] `S` `Q` ↓
  - *Problem:* _site.yml line 5 sets description: "Notes on challenging technical things" — this is the single string that becomes the homepage <meta name=description>, the OpenGraph/Twitter card text, and the search-result snippet for the whole site. It is exactly the generic-template copy the de-Quarto goal wants gone: "challenging technical things" is abstract, slightly awkward, and says nothing specific about ML/stats/math or who Andreas is. It also collides with a SECOND, different description injected via index.tmd's include-in-header meta ("MSc student in Machine Learning..."), so the site currently carries two competing self-descriptions.
  - *Fix:* Rewrite _site.yml `description` to one specific, human line reused as the OG/meta default, e.g. "Andreas Bogossian — MSc student at Aalto working through machine learning, statistics, and the math behind them, one post at a time." or tighter: "Working through machine learning, statistics, and algorithms from first principles." Then delete the duplicate meta-description injection in index.tmd (lines 9-11) so there is one source of truth. Framework note: the site engine should emit the meta description from `description` automatically so authors never hand-inject it.

- [ ] `#homepage-hero-generic` **Homepage hero repeats the name and offers no tagline — the marketing site's own structure is the fix** — `P2` [content+framework] `M` `Q` ↓
  - *Problem:* On the homepage (index/laptop__dark.png, index/mobile__dark.png) the nav brand reads "Andreas Bogossian" and the hero immediately repeats "Andreas Bogossian" in large type, then a single dry sentence: "MSc student in ML, Data Science and AI at Aalto University. I write about machine learning, statistics, and algorithms." The whole first viewport carries the name twice and a topic list — no angle, no personality, nothing memorable. Compare the native Taliesin marketing site (site/index/laptop__dark.png), which uses a three-part hero: eyebrow ("MARKDOWN IN · LIVE HTML OUT"), a confident headline ("Technical writing at the speed of code"), and a lead. The blog's `about: template: jolla` gives only name + one bio line and no tagline slot, so the personal brand has no headline of its own.
  - *Fix:* Give the homepage a real positioning line and stop repeating the bare name as the only large text. Rewrite index.tmd's body line to lead with an angle, e.g. "I'm an MSc student at Aalto working at the intersection of mathematics and production software. This is where I think out loud about the ML, statistics, and algorithms I'm learning." Framework-default: extend the about/hero front-matter (or the `about:` block) to support an eyebrow/tagline sibling to the name — the same eyebrow+headline+lead the marketing hero already renders — so every Taliesin personal site can carry a headline instead of just a name. This is the highest-leverage single change for the "make it his own / more like Taliesin" goal.

- [ ] `#three-inconsistent-bios` **Three different self-descriptions across home, CV, and blog dilute the positioning** — `P2` [content] `S` ↓
  - *Problem:* Andreas describes himself three different ways. Homepage (index.tmd:21): "MSc student in ML, Data Science and AI at Aalto University. I write about machine learning, statistics, and algorithms." CV (cv.tmd:13): "M.Sc. student at Aalto University specialising in machine learning and mathematics. I build systems at the intersection of math and production-quality software." Blog (blog.tmd:12): "I write about concepts I'm working to understand, mostly machine learning, statistics, and algorithms." The CV line is by far the strongest and most distinctive ("systems at the intersection of math and production-quality software") yet it is the one buried on the least-visited page, while the weakest, most generic version is the homepage headline a recruiter sees first.
  - *Fix:* Pick ONE confident positioning sentence and use it verbatim as the homepage lead and the CV opener; keep the blog's warmer "concepts I'm working to understand" framing as the blog-page-only voice. Suggested canonical line for home + CV: "MSc student at Aalto University working at the intersection of mathematics and production software — machine learning, statistics, and the algorithms underneath." Consistency here reads as intentional personal brand rather than three drafts.

- [x] `#cv-lists-quarto-not-taliesin` **CV lists "Quarto" (the tool he left) as a skill and omits Taliesin (the tool he built)** — `P2` [content] `S` `Q` ↓
  - *Problem:* cv.tmd:40 lists Tools as "Git, Ubuntu, Quarto". Andreas has fully left Quarto and this entire site now runs on Taliesin, a document-rendering dev server he built himself. Advertising Quarto on the CV is both factually stale and a wasted brand signal: "I built my own .tmd→HTML dev server with incremental block rendering and a warm Jupyter kernel" is one of the most impressive, differentiating things a CS/ML student can put on a CV, and it's currently invisible. Also visible on cv/laptop__dark.png in the Skills table.
  - *Fix:* Replace "Quarto" with "Taliesin" in the Tools row (cv.tmd:40), and add a one-line Projects/Experience entry framing it as authored work, e.g. "Taliesin — a Rust dev server that renders .tmd to live HTML with block-level incremental updates and a warm Jupyter kernel (author)." This turns the de-Quarto migration into a career asset rather than a stale line item.

- [ ] `#metadata-iso-date-no-readtime` **Dates render in raw ISO, there's no reading time, and categories disappear from post headers** — `P2` [framework] `M` `Q` ↓
  - *Problem:* Rendered post header is just <div class="tali-title-meta"><span>2026-05-15</span></div> (fourier post HTML) — a machine ISO date with no reading time and, notably, none of the categories that the card showed (frontmatter has categories, but the post page drops them). On the cards (blog/laptop__dark.png, index cards) dates also show as "2026-05-15". ISO dates read as system output, not editorial; "May 15, 2026" reads as a human wrote it. For a math-heavy technical blog, a reading-time estimate is a genuinely useful, human signal that recruiters and peers expect, and its absence makes every post feel unmeasured.
  - *Fix:* Framework-default (site engine, render/page.rs title-block + listing card): (1) format displayed dates as "May 15, 2026" while keeping the ISO value in a <time datetime> for machines; (2) compute and show a reading-time estimate from body word count in the post title-meta and optionally on cards; (3) surface the post's categories in the post header, not only on the card, so a reader landing on the post sees its topic tags. All three are zero-config, offline, and improve every Taliesin site — squarely "perfect the default."

- [ ] `#weak-post-descriptions` **Two post descriptions open with clichés/definitions and undersell strong posts** — `P2` [content] `S`
  - *Problem:* Most descriptions are excellent (see the keep finding), but two are the weakest cards on the blog grid (blog/laptop__dark.png). A* (a-star/index.tmd): "A* finds the shortest path between two points by balancing actual travel cost and a heuristic estimate of remaining distance." — opens by restating the term definitionally, no hook, sounds like a textbook. EM (em-algorithm/index.tmd): "A deep dive into the Expectation-Maximisation algorithm: The method behind clustering, missing data, and probabilistic models." — "A deep dive into" is filler cliché and the capital "The" mid-sentence is a typo. These sit next to genuinely great hooks and look flat by comparison.
  - *Fix:* Rewrite for hook + specificity, matching the register of the Fourier/PCA lines. A*: "How Google Maps finds the best route across millions of roads in under a second — and why a good guess beats brute force." EM: "The chicken-and-egg trick behind clustering and missing-data models: alternate between guessing the labels and fitting the distributions until both agree." Also fix the stray capital "The" after the colon in the EM description.

- [ ] `#404-copy-flat` **404 page copy is flat and off-brand** — `P3` [content] `S` ↓
  - *Problem:* 404.tmd body is "This page doesn't exist. Head back to the home page or browse the blog." It's functional but generic and shows none of the personality the rest of the site has. The 404 is a small, high-personality opportunity that most people never intentionally write.
  - *Fix:* Give it a line of voice while keeping the two escape links, e.g. "This page took a path that doesn't exist — even A* couldn't find it. Head back to the home page or browse the blog." (ties to his own A* post), or a plainer confident version: "Nothing here. This link is broken or the page moved. Try the home page or the blog." Low effort, on-brand.

- [ ] `#title-casing-inconsistency` **Post title style is inconsistent ("The EM-algorithm" vs "A* Pathfinding Algorithm" vs "KL Divergence")** — `P3` [content] `S`
  - *Problem:* Titles mix conventions: "The EM-algorithm" (lowercase hyphenated, non-standard — conventionally "The EM Algorithm"), "A* Pathfinding Algorithm" (title case, no article), "KL Divergence" (no article, no descriptor), while "PCA: the shape hidden in your data" and "The Kruskal-Wallis test, derived from first principles" carry an evocative descriptor. The bare-topic titles lean entirely on the card description for a hook, which works on cards but reads plainer as a page <h1> and in search results. Visible across blog/laptop__dark.png.
  - *Fix:* Pick one convention. Recommended: topic + short descriptor for the plain ones, and fix "The EM-algorithm"→"The EM Algorithm". e.g. "KL Divergence: measuring the distance between distributions", "A* Search: pathfinding with a good guess". Keep the already-strong PCA/Kruskal-Wallis pattern.

- [ ] `#publications-thin-framing` **Publications page frames one B.Sc. thesis as "Publications" / "Theses" (plural, slightly hollow)** — `P3` [content] `S`
  - *Problem:* publications.tmd renders a page titled "Publications" with a single "## Theses" section containing one B.Sc. thesis (cv/laptop__dark.png shows the same single item). Plural headings over one item read as an academic template waiting to be filled rather than a confident statement, and a lone-item page in the top nav can feel thin to a visitor.
  - *Fix:* Either lean in and title it honestly — heading "B.Sc. Thesis" (singular) instead of "Theses", and add a one-line lead so the page isn't just a heading + card (e.g. "My undergraduate thesis, plus talks and writing as they happen.") — or, given it duplicates the CV's Publications section, consider dropping it from nav until there is more than one item and linking the thesis from the CV only. Low priority; a judgment call for Andreas.

- [KEEP] `#keep-post-descriptions-voice` **KEEP: most post/project descriptions and the blog/projects taglines are genuinely strong** — `keep` [content] `S`
  - *Problem:* This is a decision working well and worth protecting from over-editing. The descriptions that carry the cards are specific, confident, and human: "How mathematics hears which notes are hidden in a chord" (Fourier), "why it sits at the heart of modern LLM alignment" (KL), "showing partial pooling beats complete pooling by ~1,944 ELPD" (aviation), "Regression models on 1,359 smartphones to test whether Apple devices are priced above their hardware-justified value. They are." (iPhone — the "They are." is a great confident kicker). The blog tagline "concepts I'm working to understand" and projects tagline "Things I built to learn something" show honest personality. These are the voice the weaker top-of-site strings should be raised toward.
  - *Fix:* Keep this voice. Use it as the reference register when rewriting the site description and homepage hero (see other findings) rather than inventing new copy — the good voice already exists on this site, it just isn't at the top of the funnel yet.


### Accessibility (real, post-dead-CSS)  (2 P1 · 5 P2 · 1 keep)

> The blog's real accessibility is much better than the dead custom.css suggests: base.css/dark.css already meet WCAG AA for muted text in both themes (Lighthouse color-contrast passes, and the team already stripped opacity-based muting), and the skip-link/focus-visible/forced-colors/reduced-motion foundation is genuinely strong. The substantive problems are structural, not cosmetic. (1) Every blog POST emits 7+ sibling <h1> elements (title-block h1 plus every `#` section) because Taliesin, unlike Quarto, does not shift body headings under a title block — a flat, ambiguous outline for screen-reader navigation that the migration silently introduced. (2) The footer's icon labels depend on a `.sr-only` class the framework never bundles (only `.tali-sr-only`), so they render correctly ONLY because the soon-to-be-deleted Quarto custom.css defines it: removing custom.css turns "LinkedIn/GitHub/RSS Feed" into visible text. (3) The one automated a11y failure on every page is the search button's ⌘K kbd (label-in-name mismatch), a one-line shared-chrome fix. Marketing's autoplay looping videos have no pause affordance (WCAG 2.2.2). Fixing the top three in the framework makes every Taliesin site correct by default.

- [x] `#sr-only-class-landmine` **Footer icon labels use `.sr-only`, which only the dead Quarto custom.css defines — framework bundles only `.tali-sr-only`** — `P1` [content+framework] `M` `Q`
  - *Problem:* The tech-blog footer social links are hand-authored in _site.yml as raw `<svg aria-hidden='true'>...</svg><span class='sr-only'>LinkedIn</span>` (and GitHub, RSS Feed). Those accessible names are the ONLY text on icon-only links, so they are load-bearing. But the bundled CSS defines `.tali-sr-only` (base.css:205), NOT `.sr-only`. `.sr-only` is defined ONLY in corpus/tech-blog/custom.css:9 — the Quarto-residue file the de-Quarto effort intends to delete. Delete custom.css and the visually-hidden spans become VISIBLE: literal 'LinkedIn' / 'GitHub' / 'RSS Feed' text sits next to each footer icon. This is a silent landmine sitting directly in the path of the cleanup this audit exists to enable. More broadly, `sr-only` is the universally known idiom; an author using Taliesin's HTML escape hatch with `class="sr-only"` gets broken (visible) output on a stock site.
  - *Fix:* Two-part. Framework-default: bundle `.sr-only` as an alias of `.tali-sr-only` in base.css (same visually-hidden clip rule) so author-supplied hidden text works without any custom CSS — consistent with the qmd->tali alias policy. Content-config (and the more native fix): convert the tech-blog footer to the native icon-shortcut syntax the marketing site already uses — site/_site.yml:25 writes `{ icon: github, href: ... }` and the engine emits the SVG with `aria-hidden` plus an `aria-label` on the <a>, no sr-only span needed. That requires the framework to ship `linkedin` and `rss` icons in the built-in set (marketing only exercised `github`); if they are missing, add them (framework-default). Also fix the marketing aria-label casing 'github' -> 'GitHub'.

- [x] `#search-btn-label-in-name` **Search button ⌘K kbd triggers label-content-name-mismatch — the only automated a11y fail, on every page** — `P1` [framework] `S`
  - *Problem:* The single failing automated a11y audit on every tech-blog AND marketing page (Lighthouse label-content-name-mismatch, score 0) is `.tali-search-btn`: it has aria-label='Search' but contains visible text '⌘K' (the <kbd class='tali-search-kbd'> shortcut hint). WCAG 2.5.3 Label in Name requires the accessible name to contain the visible text; '⌘K' is not in 'Search'. Voice-control users who say the visible label can't activate it. It is shared chrome (site engine), so one fix clears it site-wide on both properties.
  - *Fix:* Framework-default: add `aria-hidden='true'` to the kbd in site/chrome.rs:46 (`<kbd class='tali-search-kbd' aria-hidden='true'>`). The ⌘K badge is a decorative shortcut hint, not a label, so hiding it from the a11y tree is correct and resolves the mismatch while keeping aria-label='Search'. (The svg already carries aria-hidden.) One line.

- [ ] `#post-multiple-h1-flat-outline` **Every blog post has 7+ sibling <h1>s: title-block h1 + all `#` sections, no heading shift** — `P2` [framework] `M` `Q` ↓
  - *Problem:* corpus/tech-blog/posts/pca-geometry/index.tmd writes section headings with a single `#` (lines 97,147,200,311,366,493), and the page already emits `<h1 class="title">` from the title block. Taliesin renders `#` as literal <h1> with no level shift, so the built post contains 7 <h1> elements (verified: grep counted 7 `<h1` in the built HTML). For a screen-reader user this is a flat, ambiguous document outline: the post title is indistinguishable from its sections, and heading-by-level navigation collapses. Lighthouse heading-order PASSED (score 1) only because it flags SKIPPED levels, not repeated h1s, so this real defect is invisible to automated checks. This is a direct Quarto-migration regression: Quarto/Pandoc auto-reserve h1 for the title and shift body headings down (so `#` sections became <h2>), which is why the author's `#`-for-sections habit produced correct output there and broken output here. The blog is the priority surface and this hits every post.
  - *Fix:* Framework-default: when a page emits a title-block `<h1 class="title">` (site article layout with a `title:`), demote body Markdown headings by one level (h1->h2, h2->h3, ...) at render time, matching Pandoc/Quarto behaviour so the title is the sole h1 and sections are h2. The deck engine already reasons about heading levels (render/deck.rs block_heading_level), so the level machinery exists. Fallback if the shift is deemed too invasive: document that post sections must use `##`, but the better DEFAULT is the auto-shift so every migrated Quarto doc is correct with zero edits.

- [ ] `#autoplay-video-no-pause` **Autoplaying looping {{< video >}} demos have no pause control and ignore reduced-motion (WCAG 2.2.2)** — `P2` [framework] `M` ↓
  - *Problem:* Marketing emits `<video ... autoplay muted loop playsinline>` (no `controls`) for the live-edit and live-code screencasts (built site/index.html, two `<figure class="tali-video">`). base.css has a strong global reduced-motion rule (base.css:812-816) but it only collapses CSS animation/transition durations — it does NOT pause an autoplaying HTML <video>. So moving content plays and loops indefinitely with no mechanism to pause it, failing WCAG 2.2.2 (pause/stop/hide for moving content lasting >5s). This is also the source of marketing's agent-accessibility-tree failure (Lighthouse flags the FIGURE>VIDEO node 'ARIA role should be appropriate'). tech-blog currently uses no {{< video >}}, so this is marketing-only today, but it lives in the shared video emit.
  - *Fix:* Framework-default in the {{< video >}} emit (render/extension video handling): under `@media (prefers-reduced-motion: reduce)` do not autoplay — render the video paused showing its first frame/poster and expose native `controls` (or a pause button) so motion-sensitive users can start it deliberately. At minimum add `controls` so a pause affordance always exists. Keep autoplay+loop for no-preference users.

- [x] `#footer-icon-tap-target` **Footer social-icon links are ~16px tall — below the 24px WCAG 2.5.8 minimum tap target** — `P2` [framework] `S`
  - *Problem:* `a.tali-foot-item` (site.css:109) has no min-height/min-width; the footer social icons are 16x16 svgs (site.css:112) inside a 14px-font inline-flex link, so the actual touch target is ~16-20px tall. That is under the WCAG 2.5.8 (AA) 24x24 minimum and well under the 44px the burger correctly uses. On mobile (390px) the LinkedIn/GitHub/RSS icons sit close together in the footer, so mis-taps are likely. Lighthouse target-size passed only because it was run in desktop/navigation mode.
  - *Fix:* Framework-default: give `a.tali-foot-item` (icon links) `min-height:24px; min-width:24px` with centered content in site.css (or 44px to match the burger and hit AAA). Keep text footer items unaffected. Small, benefits every site's footer.
  - *Landed 2026-07-11 (`5fc7265`, local main):* `a.tali-foot-item:has(svg) { min-height:24px; min-width:24px; justify-content:center }` — scoped to icon links only via `:has(svg)`, so the copyright + "Source" text items are untouched (per the audit's "keep text footer items unaffected"). Chose 24px (the AA floor) over 44px so the slim footer keeps its proportions. Browser-measured 24×24 at 390px + 1440px in both themes; the 16px glyph is unchanged.

- [ ] `#code-figure-empty-alt` **Code-cell figures default to alt=""; a plot with no fig-cap is invisible to screen readers** — `P2` [framework] `M`
  - *Problem:* Generated figures render as `<img class="tali-fig ..." alt="" src="data:image/png...">` (built pca post). Where a `fig-cap:` is present (as in the PCA post), the <figcaption> is announced and the empty alt is a defensible non-redundant pattern — that is fine. But the default is decorative alt="" regardless of whether a caption exists, so a matplotlib/Plot figure emitted WITHOUT a fig-cap conveys nothing at all to assistive tech: the reader hears silence where a load-bearing plot sits. For a data-science blog whose posts are largely figures, that is a real gap the author can't easily patch (the image is code output, not authored HTML).
  - *Fix:* Framework-default: when a code-cell figure has a `fig-cap`, mirror it into the img `alt` (or leave alt="" only when a figcaption is present, which is the accessible-name source); when a figure has NEITHER alt nor caption, emit a build-time warning (like the frontmatter typo lint) so the author knows a plot is inaccessible. Keep the caption-as-description pattern where a caption exists.

- [x] `#rss-and-audio-broken-controls` **Footer 'RSS Feed' link and supercollider <audio> are accessible controls pointing at 404s / lacking transcripts** — `P2` [content] `S` `Q`
  - *Problem:* Two labeled controls betray AT users. (a) The footer emits an icon link with accessible name 'RSS Feed' (_site.yml:47) pointing at /blog.xml, which the build never produces (F4) — a screen-reader user is explicitly promised a feed that 404s. (b) The supercollider-mcp project embeds `<audio controls>` for choir_demo_v3.mp3 and voltage.mp3 which 404 in the build (F5), and audio-only content has no transcript or text description (WCAG 1.2.1) even when it loads. A control that announces itself but leads nowhere is worse than no control.
  - *Fix:* Content-config: until a feed exists, remove the RSS footer item (and its sr-only label) rather than advertise a dead link; re-add it when the site gains feed config (Taliesin can emit feeds). For the audio: fix the asset copy (F5) and add a one-line caption/description of each sound (e.g. 'Generated choir texture, ~8s') so the audio-only demo has a text alternative. Overlaps F4/F5 but flagged here because both are named, focusable controls.

- [KEEP] `#keep-real-contrast-and-focus-foundation` **KEEP: muted-text contrast meets AA in both themes and the skip/focus/reduced-motion foundation is solid** — `keep` [framework] `S` `Q`
  - *Problem:* The dead custom.css 'contrast fixes' (color:#c8d0d8 on .listing-category/.nav-footer, F1) targeted Quarto classes that never render, yet the REAL muted text is already AA-compliant: --tali-muted is #555 on #fff (~7.5:1) in light and #9aa0aa on #16181d (~6.8:1 page / ~5.9:1 on the #21242b-equivalent card surface) in dark; Lighthouse color-contrast scores 1 on every page. The team already removed the opacity-based count muting that had dropped to 2.56-3.34:1 (site.css:150 comment), so no text relies on opacity. Separately, base.css ships a correct `.tali-skip` -> `#tali-main` (main has tabindex=-1), a token-driven `:focus-visible` outline on all interactive roles, a forced-colors/prefers-contrast block, and a global reduced-motion rule. This is a genuinely strong native a11y baseline.
  - *Fix:* Keep these as-is. Concretely: this proves deleting corpus/tech-blog/custom.css will NOT regress contrast (its color fixes were inert and the real values already pass), so the de-Quarto cleanup is safe on the contrast axis — provided the `.sr-only` alias finding is handled first. Do not reintroduce opacity for muted text; keep tuning via the --tali-muted token per the existing AA-verified comments.


### Performance & offline-first integrity  (5 P1 · 4 P2 · 3 keep)

> Taliesin's zero-CDN/offline-first promise holds at runtime: across all 12 tech-blog captures and all 5 marketing captures, ZERO external hosts were contacted (F3's preconnects fetch nothing; KaTeX fonts, CSS, JS, images are all bundled). The real performance problems are self-inflicted weight, not phoning home. The single biggest lever is that site-mode builds inline everything per page: ~95KB of framework CSS + ~65KB of JS on every page, plus ~347KB of base64 KaTeX fonts (the FULL 20-file set, base64-inflated) on every math page, none of it cacheable across navigations. The blog then bolts on three overlapping Quarto-era nav-accelerators (dead CDN preconnects + speculationrules prerender + instantpage.js + @view-transition) partly to paper over that non-caching, while the native marketing reference site uses none of them. Two genuine bugs: two 404 audio files on the SuperCollider project page, and a silently-swallowed RSS feed the author configured but the framework can't generate. The LCP setup (preloaded, sized profile.webp) and the conditional heavy-lib loading (d3/Plot only on the 6 {js} pages; mermaid runtime on zero) are done well and should stay.

- [ ] `#site-build-inlines-shared-assets` **Site build inlines ~95KB CSS + ~65KB JS into every page instead of one cached file** — `P1` [framework] `L`
  - *Problem:* In multi-page site output (build <dir>), page.rs assembles the framework CSS as a single inline <style> ({base}{dark}{site}{bare_theme}) plus large inline <script> blocks, so every page carries ~95KB of identical CSS (measured block 0 = 94,729 bytes in index.html) and ~65KB of inline JS. Across ~15 tech-blog pages that is >2MB of byte-for-byte-duplicated, non-cacheable payload. Navigating post A -> post B re-downloads and re-parses the whole design system even though it never changed. The framework already CAN externalize (search-index.js 80KB, hover-index.js 22KB, instantpage.js are emitted as shared files), so this is a deliberate choice that is right for single-file `build <file>` (portable) but wrong for a site. It is also why the blog needed to bolt on prerender: a prerendered page re-parses 95KB inline CSS instead of hitting a warm cache.
  - *Fix:* In page.rs, when rendering a SITE (build <dir>), emit the concatenated base+dark+site+theme CSS and the shared client JS to content-hashed files under _site/assets/ (e.g. tali.<hash>.css, tali.<hash>.js) and reference them with <link rel=stylesheet>/<script src> so they cache across navigations and gzip once. Keep full inlining only for the single-file `build <file>` path (self-contained portability). Gate on the same Site vs single-doc branch that already governs with_site_css. This is the highest-leverage default change for any multi-page Taliesin site (the marketing site pays the same tax: index.html 677KB, showcase.html 1.16MB).

- [ ] `#katex-full-fontset-inlined-per-page` **Entire KaTeX font set (~347KB base64) inlined into every math page, uncached** — `P1` [framework] `L` ↓
  - *Problem:* Every page containing math inlines the COMPLETE KaTeX font set as base64 data URIs: 20 @font-face blocks (KaTeX_Main x4, Math x2, AMS, Caligraphic x2, Fraktur x2, Script, Size1-4, Typewriter) totalling 346,872 bytes of base64 (~260KB of actual woff2, inflated 33% by base64) on EVERY math page. Measured identical 346,872 B on both posts/KL-divergence (738KB page) and posts/pca-geometry (1.7MB page). A typical post uses maybe 4-5 of those faces, so ~200KB is unused glyph data, and because it is inlined the browser cannot (a) fetch only the referenced subset or (b) cache it across the many math pages of a math-heavy blog. For a blog whose whole identity is ML/statistics/math, this is the dominant repeat-navigation cost.
  - *Fix:* Emit the KaTeX woff2 files as real shared assets under _site/assets/katex/ and reference them from a single external KaTeX stylesheet (also cached). The browser then downloads only the font files actually referenced by rendered glyphs, once, and caches them for the entire site. This is the same externalization branch as the CSS finding but higher impact per byte. Keep base64 inlining only for single-file `build <file>`. See crates/core/src/math.rs / page.rs KATEX_CSS assembly.

- [x] `#dead-cdn-preconnects` **Three dead CDN preconnects in the blog head cut against offline-first** — `P1` [content] `S` `Q`
  - *Problem:* _site.yml head.text injects <link rel=preconnect> to cdn.jsdelivr.net, fonts.googleapis.com, and fonts.gstatic.com (rendered at build/tech-blog/index.html:1727-1729). Taliesin bundles all fonts and vendored JS, so these hosts are contacted zero times (verified across every capture). They are pure Quarto residue: they open speculative TCP/TLS connections to Google/jsDelivr on every page load that do nothing but leak the visitor's IP to three third parties and directly contradict the site's own no-referrer / offline-first stance. The native marketing site has none of them.
  - *Fix:* Delete the three preconnect <link> lines from corpus/tech-blog/_site.yml head.text (lines 12-16). No replacement needed; nothing local is served from those origins.

- [x] `#broken-audio-404` **Two <audio> mp3 files 404 on the SuperCollider project page** — `P1` [content] `S` ↓
  - *Problem:* projects/supercollider-mcp/index.tmd declares two <audio><source> elements (choir_demo_v3.mp3 line 75, voltage.mp3 line 85) but neither file exists anywhere under corpus/tech-blog (find -iname '*.mp3' returns nothing). The build produces two empty audio players and every load fires 404s (all 12 site-wide 4xx responses are these two files, 2 per capture x 6 captures). On a page whose entire point is demonstrating audio synthesis, the demos are silently broken, which reads as an unfinished portfolio to a recruiter.
  - *Fix:* Add the two mp3 files under corpus/tech-blog/projects/supercollider-mcp/ (they will be copied to _site automatically), or remove the <audio> blocks if the clips no longer exist. If keeping audio, also add preload="none" so the clips do not compete for bandwidth on load. Consider a Taliesin build-time warning when a referenced same-origin local asset is missing (framework-default follow-up), mirroring how it already special-cases the RSS .xml link.

- [x] `#no-native-feed-rss-swallowed` **Configured RSS link is silently dropped; no native feed generation** — `P1` [content+framework] `L` `Q`
  - *Problem:* Correcting F4: the built footer does NOT 404, because chrome.rs:181-192 explicitly drops any configured local .xml link ('this build generates no RSS feed'). The rendered footer contains zero blog.xml/RSS references (grep = 0). So the actual defect is different and worse for identity: the author added a full RSS icon SVG to _site.yml footer.right (line 47-48) intending a feed, and Taliesin silently swallows the entire footer item, leaving only LinkedIn + GitHub. A technical blog's audience (developers, researchers) are exactly the people who still use feed readers, and Taliesin already has all the data (the dated post listing) needed to emit a feed. The framework has no feed capability at all (grep for rss/atom/feed in site/ finds only the drop logic).
  - *Fix:* Framework: add native Atom/RSS generation for site listings (emit _site/blog.xml from the same post index that powers the listing + Cmd-K search), then honor the configured .xml footer link instead of dropping it. 'Perfect the default': a blog with dated posts should get a feed for free, no knob. Content: once shipped, the author's existing RSS icon just works; until then, remove the dead RSS footer item from _site.yml:47-48 so the intent is not misleading.

- [ ] `#redundant-nav-prefetch-stack` **instantpage.js is obsolete and redundant with speculationrules prerender** — `P2` [content] `S` `Q` ↓
  - *Problem:* The blog stacks THREE Quarto-inherited navigation accelerators that the native marketing site uses none of: (1) a speculationrules prerender script (head, href_matches /*, eagerness moderate), (2) /instantpage.js loaded as a module at body-end (11,672 B), and (3) @view-transition{navigation:auto} in custom.css. instantpage.js predates the Speculation Rules API and does the exact same job worse: it injects <link rel=prefetch> on hover, while the prerender rule already prerenders (a strict superset of prefetch) on hover. Running both means every hovered link is fetched twice by two mechanisms. It is dead weight and a redundant code path, and it is separate from Taliesin's own hover-index.js (which is the equation/theorem hover-PREVIEW data, not link prefetch, and should stay).
  - *Fix:* Delete the body-end.text script from corpus/tech-blog/_site.yml (line 26) and drop the instantpage.js file. Keep exactly one modern mechanism: the speculationrules prerender (native to Chromium, zero-JS, offline-safe) plus @view-transition for the animation. This removes a request and a whole legacy JS path with no loss of behavior.

- [ ] `#prerender-eagerness-on-heavy-posts` **moderate-eagerness prerender fires 1.7MB JS-heavy posts on hover** — `P2` [content+framework] `S` `Q`
  - *Problem:* The prerender rule matches /* with eagerness:moderate, i.e. it prerenders any same-origin link the pointer hovers/lingers on. The blog's post pages are the heaviest documents on the site (posts/pca-geometry 1.7MB, posts/em-algorithm 1.77MB) because they inline d3 (~280KB), Plot, and base64 matplotlib PNGs (476KB on pca-geometry). Prerendering executes the target page's scripts in the background, so idly hovering the blog listing can spin up d3/Plot reactive graphs for several 1.7MB pages at once, burning CPU/memory/battery for pages the reader may never open.
  - *Fix:* Either lower eagerness to conservative (prerender on pointerdown, not hover) in _site.yml, or scope the where clause to cheap routes and exclude posts/*. Better framework default: if Taliesin adopts prerender natively (see below), default it to conservative and let content pages that inline a JS runtime opt out. Pair this with externalizing d3/Plot (see conditional-lib keep) so a prerendered page reuses cached libs instead of re-parsing 280KB inline.

- [ ] `#matplotlib-png-not-webp` **Executed-cell figures embed as base64 PNG (476KB on one post), not webp** — `P2` [framework] `M`
  - *Problem:* The kernel emits matplotlib figures as base64 PNG data URIs. On posts/pca-geometry that is 6 images totalling 476,844 bytes of base64 (~360KB binary) inlined into the page, the single largest non-font contributor to its 1.7MB weight. PNG is a poor format for the anti-aliased line/scatter plots these posts contain; the same figures as webp are typically 40-70% smaller. Because they are inlined base64, they are also uncached across pages and base64-inflated by 33%.
  - *Fix:* Framework: have the executor/render path prefer webp for raster cell outputs (or emit them as external cached files under _site/assets/, which also lets the browser lazy-load below-the-fold figures). Even keeping PNG, writing them as external files rather than inline base64 removes the 33% base64 tax and enables loading=lazy. Lower priority than the CSS/KaTeX externalization but shares the same fix.

- [ ] `#custom-css-render-blocking-mostly-dead` **custom.css is a render-blocking request that is ~80% dead and duplicates base.css** — `P2` [content+framework] `S` `Q` ↓
  - *Problem:* From a performance angle (F1 covers the deadness in detail): custom.css is an extra 9,105-byte render-blocking <link> on every page, yet most of it targets Quarto/Bootstrap selectors Taliesin never emits (.quarto-grid-item, #TOC.toc-inline, .back-to-top, #quarto-margin-sidebar, .listing-category, --bs-primary). The handful of live rules that remain (img/pre/table/.katex overflow-x:auto, max-width:100%) largely DUPLICATE rules already present in the inlined base.css, so the browser downloads and applies a mostly-inert stylesheet that competes with first paint for no visual gain. The @font-face for 'bootstrap-icons' (src:local only) is also inert.
  - *Fix:* Delete custom.css and its css: reference in _site.yml. Verify the ~4 genuinely-live overflow rules already exist in base.css (they appear to); if any is missing, add it to base.css so every Taliesin site gets the mobile overflow behavior by default rather than via a per-site file. This removes a request and eliminates a stale Quarto surface.

- [KEEP] `#offline-first-verified` **Zero-CDN promise holds: no external request on any page, both sites** — `keep` [framework] `S`
  - *Problem:* The core offline-first invariant is actually met at runtime. Aggregating the network logs of all 12 tech-blog captures and all 5 marketing captures, the count of non-localhost hosts contacted is 0. KaTeX fonts are inlined as data:font/woff2 base64, all CSS/JS is bundled, profile.webp/og-image.webp/bell-curve.svg are local, and the meta referrer is no-referrer. The three CDN preconnects in the blog head resolve to nothing because nothing is ever fetched from those hosts.
  - *Fix:* Keep the bundling architecture. It is the framework's strongest differentiator and it works. Do not regress it by pulling any asset to a CDN. The findings below are about redundant local weight and dead hints, not about anything phoning home.

- [KEEP] `#lcp-profile-webp-good` **LCP handling of the home profile image is correctly tuned** — `keep` [content] `S`
  - *Problem:* The home page's LCP element is well handled: profile.webp is 400x400 and only 17,856 bytes, preloaded with <link rel=preload as=image fetchpriority=high> (index.html:1747), and the preload is emitted ONLY on index.html (not blindly on every page), so no page preloads an image it does not show. The rendered <img class=tali-about-img> has no width/height attributes, but site.css:158 fixes it to width:9rem;height:9rem, so its box is reserved before load and there is no CLS. og-image.webp is a correct 1200x630.
  - *Fix:* Keep as-is. This is a textbook LCP setup (small modern format, high-priority preload, page-scoped, layout-stable). Do not add width/height to the about img specifically since CSS already reserves the box.

- [KEEP] `#conditional-heavy-lib-loading-good` **d3/Plot load only where used; mermaid runtime ships on zero pages** — `keep` [framework] `S`
  - *Problem:* Heavy-library loading is scoped correctly, contradicting the fear behind F9. d3 (~280KB) and plot.umd are embedded only on the 6 post pages that actually contain {js} cells (pca-geometry, fourier-transform, em-algorithm, a-star, evidence-lower-bound, Kruskal-Wallis) and are absent from all listing/project/no-viz pages. The mermaid RUNTIME ships on zero tech-blog pages: no page contains a pre.mermaid element or mermaid.initialize, so the 2.5MB library is never emitted (only ~1KB of pre.mermaid CSS lives in the inline stylesheet). This per-page conditional bundling is exactly right.
  - *Fix:* Keep the conditional inclusion logic. The only refinement (already covered by the externalization findings) is that when d3/Plot ARE included they should become shared cached files rather than per-page inline copies, so a reader who opens two {js} posts fetches d3 once. Do not load them globally.


### SEO, metadata, structured data & discoverability  (5 P1 · 4 P2 · 1 P3 · 1 keep)

> The framework's per-page metadata layer (crates/core/src/site/meta.rs) is genuinely strong: every page gets a unique canonical URL, og:type=article for dated posts, per-post description + thumbnail og:image (summary_large_image), and even a Google-Scholar citation_* path. But three high-leverage discoverability primitives are entirely MISSING by default: JSON-LD structured data (0 ld+json blocks on every page), a sitemap.xml, and a robots.txt (neither exists in either build). The blog also ships two real bugs that hurt the career-facing brand: the home page emits TWO conflicting <meta name="description"> tags (its social card shows the weak "Notes on challenging technical things" instead of the MSc positioning), and the footer's RSS link points at /blog.xml which 404s because no feed is generated. Secondary weaknesses: home and CV share the identical <title>Andreas Bogossian</title>, listing/section pages carry no site-name context, posts emit 7 <h1>s each (flat outline), and the citation_* scholarly path is silently inert because no post or site config declares an author. Most fixes belong in the Taliesin default (sitemap/robots/feed/JSON-LD) so every site benefits; a handful are Quarto-residue the author should delete from his .tmd frontmatter.

- [x] `#no-json-ld-structured-data` **Zero JSON-LD structured data on any page (no Person / BlogPosting / BreadcrumbList / WebSite)** — `P1` [framework] `M`
  - *Problem:* grep 'application/ld+json' returns 0 blocks on every built page (home, blog, cv, publications, projects, all posts, marketing home). For a career-facing academic/ML profile this is the single biggest missed lever: no Person schema means Google gets no author entity to attach to a Knowledge Panel or to link the author of each post; no Article/BlogPosting means posts are ineligible for article rich results and lose byline/date attribution; no BreadcrumbList means SERP breadcrumbs never render; no WebSite+SearchAction means no sitelinks search box. Everything a JSON-LD block needs is ALREADY computed in site/meta.rs (title, description, absolute page_url, absolute image, date, authors, site title) — it is emitted as flat <meta> but never as a graph.
  - *Fix:* In crates/core/src/site/meta.rs, alongside social_head(), emit a <script type="application/ld+json"> block from the SAME resolved fields: a BlogPosting/Article (headline=title, description, datePublished=page.date, image, mainEntityOfPage=canonical, author=Person) whenever page.date.is_some(); a Person schema on the site's about/home + CV pages (name from cfg.title, url, sameAs=[GitHub, LinkedIn from footer], jobTitle/affiliation); and a WebSite node with the search action on the root. Add BreadcrumbList from the page's URL path segments. On the marketing site emit SoftwareApplication for Taliesin. This is a framework default (perfect-the-default), keyed off data already in the Page/Site structs.

- [ ] `#duplicate-home-description` **Home page emits two conflicting <meta name="description"> tags; the social card shows the weaker one** — `P1` [content] `S` `Q`
  - *Problem:* build/tech-blog/index.html contains TWO description tags: content="Notes on challenging technical things" (site default) AND content="MSc student in Machine Learning, Data Science and AI at Aalto University..." (the good one). Root cause: index.tmd uses Quarto's include-in-header idiom to hand-inject the MSc description, while the site engine independently emits the site-level default because index.tmd has no native description: key. Crawlers may pick either. Worse, og:description AND twitter:description both use the WEAK default ("Notes on challenging technical things") because they read doc.description, so when Andreas shares his own homepage on LinkedIn the card headline is the vague default, not his MSc positioning — directly undercutting goal #1 (forward-facing personal brand).
  - *Fix:* In corpus/tech-blog/index.tmd: delete the entire include-in-header: block and add a native frontmatter key description: "MSc student in Machine Learning, Data Science and AI at Aalto University. I write about ML, statistics, and algorithms." This yields a single description AND propagates the good copy into og:description/twitter:description (posts already prove the native key works). Keep the preload for profile.webp by moving it to _site.yml head: or a supported preload path, not include-in-header.

- [x] `#missing-sitemap-robots` **No sitemap.xml and no robots.txt are generated for either site** — `P1` [framework] `M` `Q`
  - *Problem:* find over both build dirs returns no sitemap.xml and no robots.txt. A brand-new personal domain (andreasbogossian.com) benefits materially from a sitemap to get its posts crawled and indexed quickly, and a robots.txt is the conventional place to advertise the sitemap. Quarto emitted sitemap.xml by default when a site url: was set, so dropping it is a regression against the pre-Quarto-exit baseline. Taliesin already knows every output page URL and the absolute site url: at build time (it builds canonical URLs in meta.rs), so it has everything needed.
  - *Fix:* Framework default in the site build (crates/core/src/site/mod.rs build path): when cfg.url is set, write sitemap.xml listing every non-draft page's canonical URL (reuse the same clean-directory URL logic as meta.rs; add lastmod from page.date where present) and a robots.txt containing `User-agent: *\nAllow: /\nSitemap: <url>/sitemap.xml`. Add `<link rel="sitemap">` optional. No config knob needed — emit whenever url: exists.

- [x] `#broken-rss-feed-link` **Footer RSS link points at /blog.xml which 404s (no feed is generated)** — `P1` [content+framework] `M` `Q` ↓
  - *Problem:* _site.yml footer right[] includes an RSS icon linking href: /blog.xml, but no .xml file exists anywhere in the build (confirmed by find). Every reader who clicks the RSS icon hits a 404 — an embarrassing dead link on a personal brand site. There is also no <link rel="alternate" type="application/rss+xml"> in any page head, so feed-reader auto-discovery fails too. Taliesin has all the data a feed needs (post titles, dates, descriptions, canonical URLs) but generates nothing.
  - *Fix:* Best default: generate the feed. Framework-default — during the site build, when a posts listing exists, emit an Atom/RSS file (e.g. blog.xml or feed.xml) from the listing's entries (title, canonical link, date, description) and inject `<link rel="alternate" type="application/atom+xml" href=...>` into head for auto-discovery. Until that ships, the content-config stopgap is to remove the RSS <svg>/href /blog.xml item from _site.yml footer.right so nothing 404s. Do not ship a dead link.

- [ ] `#duplicate-generic-titles` **Home and CV share identical <title>; listing pages carry no site-name context** — `P1` [content+framework] `M` `Q`
  - *Problem:* build/tech-blog/index.html and cv.html BOTH render <title>Andreas Bogossian</title> — a title collision that makes the two pages indistinguishable in tabs, SERPs, and bookmarks. Listing/section pages render bare <title>Blog</title>, <title>Projects</title>, <title>Publications</title>, <title>Page not found</title> with zero brand context, so a SERP result for a post-listing reads just "Blog" with no owner. cv.tmd title is literally "Andreas Bogossian" (frontmatter). Quarto suffixed page titles with the site title by default (title-prefix / pagetitle); Taliesin's resolve_title (page.rs:254) emits the bare title with no site-name join.
  - *Fix:* Framework default (page.rs resolve_title / the site title assembly): for a site page that is NOT the root/home, emit `<title>{page title} · {site title}</title>` (e.g. "Blog · Andreas Bogossian", "CV · Andreas Bogossian"), leaving the home page as just the site title. Skip the suffix when page title already equals the site title. Content stopgap: give cv.tmd a distinct title: "Curriculum Vitae". This is perfect-the-default: no knob, better SERP/tab identity for every Taliesin site.

- [ ] `#og-article-namespace-and-author-missing` **og:type=article on posts but no article:* namespace and no <meta name="author"> anywhere** — `P2` [framework] `S`
  - *Problem:* Posts correctly set og:type=article, but the built head has no article:published_time, article:modified_time, article:author, article:section, or article:tag — even though the post frontmatter carries date: and categories: that map directly onto article:published_time and article:tag. There is also no <meta name="author"> on any page. LinkedIn/Facebook/Slack unfurlers and some search features read the OG article namespace; omitting it leaves the article card date-less and tag-less.
  - *Fix:* In site/meta.rs, when og_type=="article": emit article:published_time from page.date (ISO 8601), one article:tag per category, and article:author from the resolved author. Add a global `<meta name="author">` (site-level author, see the citation finding). All source data already exists on the Page struct (date, categories). Framework default, keyed off existing fields.

- [ ] `#citation-meta-dead-no-author` **Google Scholar citation_* meta path is silently inert because no author is configured** — `P2` [content+framework] `S`
  - *Problem:* site/meta.rs emits scholarly citation_title/citation_author/citation_publication_date/citation_journal_title ONLY when page.authors is non-empty. But no post declares author: (verified: grep '^author' across corpus/tech-blog/posts = none) and _site.yml has no site-level author, so page.authors is always empty and citation_* is NEVER emitted (grep on the built post confirms zero citation_ tags). A well-intentioned feature aimed exactly at this audience (an ML MSc student indexable in academic databases) is dead in practice.
  - *Fix:* Two parts. Content-config: add author: Andreas Bogossian to _site.yml (site-wide default) so every post inherits an author. Framework-default: in meta.rs, fall back page.authors -> site author -> site title so the scholarly path is not silently disabled by a missing key (perfect-the-default: the feature should work out of the box, not require an undocumented per-post key). This also unblocks the article:author and <meta name="author"> from the previous finding.

- [ ] `#multiple-h1-per-post` **Posts emit 7 <h1> elements each, flattening the document outline for search and screen readers** — `P2` [content+framework] `S` `Q`
  - *Problem:* build/tech-blog/posts/pca-geometry/index.html has 7 <h1> tags: the frontmatter title renders <h1 class="title"> AND every section heading is also <h1> because the author writes single-# headings (index.tmd lines 55/97/147/200/311 are `# Section`). A page with many h1s has no heading hierarchy — search engines and assistive tech cannot derive an outline, and the visual/semantic emphasis of the real title is diluted. This is Quarto-inherited authoring habit (Quarto shifted heading levels under the title automatically; Taliesin renders # as h1 literally).
  - *Fix:* Content-config: use ## for post sections (### for subsections), reserving the single h1 for the title block. Framework-default: add a `taliesin check` lint that warns when body-level `#` headings coexist with a title-block h1 (catch the broken outline at author time rather than silently emitting 7 h1s) — perfect-the-default via a warning, not a surprising auto-demotion that would violate the single-editing-surface principle.

- [ ] `#listing-page-no-h1` **The blog listing page renders zero <h1> (its title is suppressed by Quarto title-block-style: none)** — `P2` [content+framework] `S` `Q`
  - *Problem:* build/tech-blog/blog.html has H1 count = 0 — the primary posts-listing landing page has no heading at all, and the intro sentence floats headingless. Cause: blog.tmd sets title-block-style: none (a Quarto idiom) which Taliesin honors by not rendering the title h1, combined with page-layout: full. A top-level indexable page with no H1 is a weak SEO signal (search engines lean on the H1 as the page's topical anchor) and a poor accessibility landmark.
  - *Fix:* Content-config: remove title-block-style: none (Quarto residue) from blog.tmd so the "Blog" title renders as the page h1. Framework-default consideration: a titled listing/landing page should still emit exactly one h1 for the title even under a minimized title block, so no Taliesin site accidentally ships a headingless landing page.

- [ ] `#dead-cdn-preconnect-head` **Head injects three preconnects to CDN/font hosts that are never contacted** — `P3` [content] `S` `Q`
  - *Problem:* _site.yml head: injects preconnects to cdn.jsdelivr.net, fonts.googleapis.com, and fonts.gstatic.com, but Taliesin bundles fonts offline and capture recorded zero external requests. Unused preconnects are dead weight in the head and trip the Lighthouse 'uses-rel-preconnect' best-practice hint (preconnect to origins the page never uses). It is also pure Quarto residue that cuts against the offline-first invariant.
  - *Fix:* Content-config: delete the three preconnect <link>s from _site.yml head:. (The speculationrules/instantpage prefetch stack in the same block is a separate perf/nav concern covered elsewhere; at minimum the font/CDN preconnects should go since nothing on the page ever hits those hosts.)

- [KEEP] `#per-post-og-canonical-good` **KEEP: per-post unique description, canonical directory URL, og:type=article and per-post card image** — `keep` [framework] `S`
  - *Problem:* This is a genuinely strong, non-generic default worth validating and preserving. Each post gets a unique, well-written <meta name="description"> from native frontmatter, og:type=article, a clean canonical directory URL (https://andreasbogossian.com/posts/pca-geometry/ — index.html stripped), a per-post og:image thumbnail (thumbnail.webp/png, all present in the build), and twitter:card=summary_large_image. That is well above a copied template and exactly the shape a shared post should have.
  - *Fix:* No change. Keep site/meta.rs's per-page description/image/canonical fallback logic as-is; build the JSON-LD and article:* additions ON TOP of this foundation rather than replacing it. The one adjacent fix is ensuring the default site og-image.webp (used by non-post pages) is a strong, on-brand card since it is what represents the homepage share.


### Responsive & cross-viewport behaviour  (2 P2 · 4 P3 · 2 keep)

> Both sites are structurally sound across the three viewports: domFlags report horizontalOverflow:false everywhere, code/math/tables scroll inside their own blocks rather than the page, the nav burger is a well-built 44px target, and the blog's LISTING grid reflows cleanly from 3 cols (laptop/portrait) to 1 col (mobile). The real weaknesses are measure and touch-density, not breakage. The biggest is that `page-layout: full` (a Quarto idiom on the marketing landing and both blog index pages) removes the reading cap from BODY PROSE too, so explanatory paragraphs on the marketing landing run ~110ch at portrait and ~100ch at laptop, while blog POSTS (correctly capped at 46rem) prove the good measure is already available. Secondary issues: category filter chips and in-card category tags are sub-44px tap targets (card tags ~18px, below even the 24px AA floor) yet are interactive filters; project-card thumbnails force 16:9 cover-crop that mangles tall data figures; and on a JS-less site render the on-page TOC strands at the very bottom because the `order:-1` lift only exists for the single-doc format, not the site format. All are framework-default fixes that would lift every Taliesin site.

- [ ] `#full-layout-prose-runs-edge-to-edge` **page-layout:full drops the reading cap on body PROSE, not just the grid — marketing landing prose runs ~110ch** — `P2` [content+framework] `M` `Q` ↓
  - *Problem:* `page-layout: full` sets `.tali-wide { max-width: 60rem }` and applies it to ALL flow content. On the marketing landing the intro paragraph ("Taliesin is built around one idea...") therefore runs the full column: ~868px (~120ch) at portrait 900 and ~960px (~100ch) at laptop — far past the comfortable 45-75ch prose measure. Blog posts prove the site already knows the right measure (they cap at --tali-maxw:46rem and read beautifully). The blog/projects INDEX pages use page-layout:full too; today they only escape because their intro is a single sentence, but any 2-3 sentence intro there will run just as wide. The full layout is needed for the card GRID and the hero to span, but prose should not.
  - *Fix:* In the framework, make `full`/`wide` widen only the containers that want it (listings, hero, figures, feature grid, .tali-layout) and keep a prose cap. Add to site.css/base.css: `.tali-wide > main > :is(p,ul,ol,dl,blockquote,h1,h2,h3,h4) { max-width: var(--tali-maxw); }` and the equivalent `body.tali-wide > :is(...)` for the single-doc format, while explicitly exempting `.tali-listing`, `.tali-figure`, `.hero`, `.feature-grid`, `.tali-layout`, and `.tali-about`. This is a better default than a knob and needs no content edits. Blog posts stay unchanged.

- [x] `#category-tap-targets-too-small` **Category filter chips and in-card category tags are sub-44px (tags ~18px) but are interactive filters** — `P2` [framework] `S`
  - *Problem:* The blog/projects listing filter is driven by two touch surfaces on mobile. `.tali-cat-chip` (the top filter row) is ~25px tall (font .8rem, padding .25rem) — it clears the 24px AA floor (WCAG 2.5.8) only just and fails the 44px target (2.5.5). Worse, the per-card category tags `.tali-cat[data-cat]` are also clickable filters (cursor:pointer, toggle .tali-cat-on) yet are only ~18px tall (font .72rem, padding .1rem .55rem) — below even the 24px AA minimum. On blog/mobile the filter row is a dense two-line cluster of tiny pills that are fiddly to tap accurately, undercutting the one interactive feature of the listing on the device where it matters most.
  - *Fix:* In site.css, give the touch surfaces real target size on coarse pointers: wrap the chip/tag rules in `@media (pointer: coarse)` (or the <=640px block) and set `.tali-cat-chip, .tali-cat[data-cat] { min-height: 44px; display: inline-flex; align-items: center; }` with padding bumped to `.5rem .8rem`. Keep the compact desktop sizing. The burger already models the 44px target (site.css:172) — apply the same discipline here.
  - *Landed 2026-07-11 (`5fc7265`, local main):* `.tali-cat-chip` and `.tali-cat[data-cat]` both get `min-height:24px; box-sizing:border-box` (the card tag also gains `display:inline-flex; align-items:center` so the min-height takes effect and the label centres). **Divergence from the stated fix:** applied the 24px AA floor *unconditionally* (not 44px behind `@media (pointer:coarse)`), because (a) every `.tali-cat` card tag always carries `data-cat` (mod.rs:1114) so there is no non-interactive variant to protect, and (b) a hard 44px pill on the priority listing reads chunky and desktop-heavy; 24px clears WCAG 2.5.8 (AA) while staying visually restrained. Browser-measured chips 25px / tags 24px at 390px + 1440px, both themes; screenshots show no chunkiness. If the author later wants the fuller 44px AAA target on coarse pointers, that's a one-line `@media (pointer:coarse)` bump on top.

- [ ] `#card-thumb-forced-16x9-crop` **Project/post card thumbnails force 16:9 cover-crop, mangling tall data figures** — `P3` [content+framework] `M` ↓
  - *Problem:* `.tali-card-img { aspect-ratio: 16/9; object-fit: cover }` hard-crops every listing thumbnail to landscape. For a data-viz blog this is the wrong default: the projects/mobile listing shows a tall Bayesian forest plot and a square iPhone correlation heatmap squeezed/cropped into 16:9, and because those figures are exported on WHITE backgrounds they render as jarring bright rectangles inside otherwise dark cards. The card grid's visual rhythm breaks and the informative parts of the figures (axis labels, legend) are what get cropped or shrunk. This is a responsive-thumbnail policy that assumes photographic hero images, not charts.
  - *Fix:* Two-part: (framework) offer the card image `object-fit: contain` with a neutral `--tali-code-bg` matte instead of cover so charts are never cropped, or reduce the forced ratio to a shorter band and center-crop less aggressively; keep cover only for true photos. (content) Andreas should export figure thumbnails with transparent/dark backgrounds so they sit in the dark card grid — a white plot on a dark card is the most visible break in the whole listing. Perfect the default first: `contain` on a matte is the safer framework default for a technical corpus.

- [ ] `#site-toc-strands-at-bottom-no-js` **With JS off, the site-format on-page TOC strands at the very bottom on mobile (no order-lift)** — `P3` [framework] `S`
  - *Problem:* The single-doc format lifts the mobile TOC above content with `body.has-toc:not(.tali-toc-sheet) > #TOC { order:-1 }` (base.css:758). The SITE format puts `has-toc` on `.tali-site-main`, not `body`, and its <=60rem rule (site.css:94-97) only collapses the grid to one column — there is NO order rule. #TOC sits after </main> in the DOM (verified in the built pca post), so a reader with JS disabled, or a crawler, gets the entire table of contents dumped after the article and before the footer. With JS on, toc-sheet.js rescues this by turning #TOC into a bottom pull-up sheet, so it only bites the no-JS path — but the framework's own progressive-enhancement comment (toc-sheet.js:26-28) says the no-JS layout must stay usable, and here it is merely reachable, not sensible.
  - *Fix:* Mirror the single-doc lift for the site format: in site.css's <=60rem block add `.tali-site-main.has-toc > #TOC { order: -1; border-bottom: 1px solid var(--tali-border); margin-bottom: 1.5rem; }` (and ensure the collapsed grid keeps the TOC and back-nav in sensible source order). Low severity because JS-on is the common case, but it is a one-line consistency fix that makes the static export self-consistent between formats.

- [ ] `#mobile-code-math-horizontal-scroll` **Post code cells (and display math) require horizontal scroll on phones instead of soft-wrapping** — `P3` [framework] `M` ↓
  - *Problem:* On the PCA post at 390px, python cell content extends to right:427-846 and is reachable only by horizontally scrolling inside the <pre>; KaTeX display math on the showcase similarly overflows to right:453. It is correctly contained (no body overflow) but two-finger horizontal scrubbing through code and equations is the worst mobile reading interaction, and this is a math/algorithms blog where code and display math are the CORE content on the device many readers arrive on. The framework already has a code line-wrapping capability (emit.rs) but it is not the mobile default here.
  - *Fix:* Make narrow viewports soft-wrap code by default: in base.css under `@media (max-width: 30rem)` (or coarse pointer) set `pre code, .tali-hl-source { white-space: pre-wrap; overflow-wrap: anywhere; }` for cells without an explicit no-wrap flag, keeping the desktop scroll behavior. For display math, ensure the katex-display scroll container shows a visible fade/scrollbar affordance so readers know it pans. Prefer the wrap default over adding a per-doc knob.

- [ ] `#portrait-3col-listing-cramped` **Listing grid shows 3 cramped columns at portrait 900 where 2 would read better** — `P3` [framework] `S`
  - *Problem:* `grid-template-columns: repeat(auto-fill, minmax(min(100%,15rem),1fr))` yields 3 columns at portrait 900 (~276px each), so card titles wrap to 2-3 lines ("PCA: the shape hidden in your data", "The Kruskal-Wallis test, derived from first principles") and descriptions become tall narrow ribbons. The 15rem min-track has no tablet-portrait 2-column intent — the layout jumps straight from 1 col (<=~500px) to 3 cols. A 2-column band would give titles and 16:9 thumbnails more room on the common tablet-portrait width.
  - *Fix:* Raise the min track so portrait tablets land on 2 columns before 3: e.g. `minmax(min(100%, 18rem), 1fr)` (pushes the 3rd column past ~900px) or add an explicit `@media (min-width:40rem) and (max-width:60rem) { .tali-listing-grid { grid-template-columns: repeat(2,1fr) } }`. Verify the laptop 3-col result is preserved. Minor polish, but it directly improves the blog's front door on tablets.

- [KEEP] `#no-overflow-baseline` **Zero page-level horizontal overflow; overflow is correctly contained in scroll blocks** — `keep` [framework] `S`
  - *Problem:* Across every captured route/viewport/theme, domFlags reports horizontalOverflow:false and scrollWidth==innerWidth. Where content is intrinsically wide (python cells at right:427 vs 390 on the PCA post; KaTeX display math at right:453 vs 390 on the showcase; site-index shell code at right:846), it overflows INSIDE its own overflow-x:auto container, never the body. The CV skills/languages tables fit at 390 with no pastRight entries and no `display:block` reflow hack. This is the hard part of responsive layout and it is done right.
  - *Fix:* Keep. Preserve base.css:427 (`overflow-x:auto` on code), the `canvas,svg,video,iframe { max-width:100% }` clamp (base.css:420), `figure.tali-figure img { max-width:100% }` (base.css:685), and `.tali-eqn-body { min-width:0 }` (base.css:693). When adding any new wide block type (wide tables, new embeds), route it through the same min-width:0 + overflow-x:auto pattern so this invariant holds. The corpus test that asserts no horizontal overflow should stay a gate.

- [KEEP] `#nav-burger-implementation` **Mobile nav collapse is a solid, WCAG-sized implementation** — `keep` [framework] `S`
  - *Problem:* At <=640px the horizontal nav collapses to a burger that is an explicit 44x44px tap target (WCAG 2.5.5), toggles a full-width dropdown panel with generous .7rem/1.15rem link padding, and the menu was correctly re-implemented off a class toggle instead of the old checkbox hack. Verified visually on blog/mobile (burger + gear), projects/mobile, and publications/mobile. Between 641-960px the full 4-item blog nav and even the 6-item marketing nav fit without crowding or wrap.
  - *Fix:* Keep. This is the reference for how the OTHER touch targets on the page should be sized (see the chips finding). Do not lower the 44px burger box.


### Code architecture, maintainability & framework defaults  (2 P1 · 6 P2 · 1 P3 · 1 keep)

> The blog's config is carrying a large volume of Quarto residue that either does nothing or actively fights Taliesin's native behavior. custom.css (352 lines) is ~95% dead: every listing/TOC/back-to-top/category/nav-footer rule targets Quarto/Bootstrap selectors Taliesin never emits, the overflow rules duplicate base.css, and one KaTeX rule is actively worse than base.css's own fix. theme.scss is fully orphaned SCSS. The _site.yml head:/body-end: blocks stack three Quarto-inherited prefetch/transition mechanisms (dead CDN preconnects, speculationrules, an 11KB instantpage.js, plus @view-transition) that Taliesin has no native equivalent for and which serve no purpose offline. Two real defect classes surface: the footer advertises an RSS feed that the engine silently drops (no feed is generated, no warning), and a shared-chrome search button fails WCAG 2.5.3 on every Taliesin site. On the credit side, meta.rs's OG/Twitter/citation head and the vocab/validator drift-lock are genuinely strong native design worth keeping. The de-Quarto path is almost entirely deletion plus a few framework defaults (feed + sitemap generation, one a11y fix, value-level lint) that would let every future site ship with an empty custom.css and a trivial head:.

- [ ] `#head-block-quarto-nav-residue` **_site.yml head:/body-end: stack three dead Quarto prefetch/transition mechanisms** — `P1` [content+framework] `S` `Q` ↓
  - *Problem:* _site.yml `head:` (L11-24) injects three preconnects to cdn.jsdelivr.net, fonts.googleapis.com, fonts.gstatic.com — Taliesin bundles all fonts offline (zero external requests recorded), so these are inert and cut directly against the offline-first invariant. The same head also injects a speculationrules prerender script, `body-end:` loads a local /instantpage.js (11,672 bytes, shipped as corpus/tech-blog/instantpage.js and copied into the build), and custom.css adds @view-transition navigation:auto. That is THREE overlapping nav mechanisms: speculationrules and instantpage.js BOTH do hover/prerender prefetch (redundant with each other), and @view-transition is a separate Chrome-only cross-doc transition. All three are Quarto-inherited; Taliesin ships no native equivalent (grep of assets + page.rs + site/ finds no prefetch/view-transition support), so none is load-bearing and all add weight/complexity for a Chrome-only, offline-irrelevant benefit.
  - *Fix:* In _site.yml delete the entire `head:` preconnect block and the speculationrules script; delete `body-end:` and the corpus/tech-blog/instantpage.js file; drop @view-transition from custom.css (which is being deleted anyway). Keep the head: key only if genuinely needed for something offline-safe. FRAMEWORK angle (perfect the default): if instant navigation is worth having, Taliesin should ship ONE native, offline-safe prefetch-on-hover in the site engine so no user ever hand-rolls instantpage.js + speculationrules — a single owned mechanism beats three inherited ones.

- [ ] `#search-btn-label-name-mismatch` **Shared-chrome search button fails WCAG 2.5.3 on every Taliesin site** — `P1` [framework] `S`
  - *Problem:* The one automated a11y failure on every page (blog + marketing + books), Lighthouse label-content-name-mismatch score 0, is the search button in shared chrome: `<button ... aria-label='Search'>` whose visible content includes `<kbd>⌘K</kbd>` (chrome.rs search_button, L43-47). The accessible name is 'Search' but the visible text is '⌘K'; WCAG 2.5.3 (Label in Name) requires the accessible name to contain the visible label text, so speech-control users saying 'click Search' works but the audit and the standard flag the visible ⌘K not being in the name. Because it is in the site engine, it regresses accessibility for EVERY site built with Taliesin.
  - *Fix:* FRAMEWORK one-line fix in chrome.rs search_button: mark the shortcut hint decorative — `<kbd class='tali-search-kbd' aria-hidden='true'>⌘K</kbd>`. The kbd is a keyboard-hint affordance, not a label, so hiding it from the a11y tree makes the accessible name ('Search') the only labelled text and clears the audit on all three sites at once. Verify with a re-run: score should go 0→1 on report.json and site/report.json.

- [x] `#custom-css-delete-to-zero` **custom.css is ~95% dead, duplicative, or actively harmful — delete it almost entirely** — `P2` [content] `S` `Q` ↓
  - *Problem:* Of custom.css's 352 lines, the overwhelming majority match zero live DOM. Confirmed dead (Quarto/Bootstrap selectors Taliesin never emits): the @font-face bootstrap-icons (L23-27, no bootstrap-icons anywhere), all .listing-category/.listing-date/.nav-footer contrast fixes (L99-131), .quarto-grid-item hover (L135-141), the entire .mobile-category-filter/.quarto-listing-category/.category block (L145-191), #listing-recent-posts (L195-198), .listing-category.active (L202-210), #quarto-margin-sidebar/#quarto-content (L213-220), the whole #TOC.toc-inline block (L228-289), and .back-to-top (L293-330). Several of these reference --bs-primary, which is undefined in Taliesin's CSS (grep of assets/css confirms it does not exist), and several set color:#c8d0d8 + opacity (hardcoded vendor-ish hex + opacity-on-text, both banned by the theme system had they been live). The overflow rules (L32-95: pre/table/img/.katex-display/cell-output) are DUPLICATIVE of base.css (base.css:368 pre overflow, :426 table, :416/:642/:685 img, :705 .katex-display). Worse, custom.css L42-48 sets `.katex-display>.katex{display:block}` — base.css:696-700 explicitly documents that this is the bug (it makes the child full-width so overflow never scrolls) and fixes it with `width:max-content`; the custom rule can REGRESS wide-equation scrolling. The only arguably-live rule is `.sr-only` (L9-19), needed solely because the footer SVGs use class='sr-only' (base.css defines `.tali-sr-only`, not `.sr-only`).
  - *Fix:* Delete custom.css entirely and drop `css: custom.css` from _site.yml. The single dependency (.sr-only, used by the footer SVGs) is removed by switching the footer to the native `icon:` shorthand (see footer-icon-shorthand finding), which emits proper aria-labels and needs no sr-only span. If the footer SVGs are kept for now, retain ONLY the .sr-only block (L9-19) and delete the other 333 lines. Do NOT keep the KaTeX/pre/table/img overflow rules — base.css already covers them and the KaTeX one is a regression.

- [x] `#theme-scss-orphan-delete` **theme.scss is orphaned Quarto SCSS — delete the file** — `P2` [content] `S` `Q` (duplicate of `#theme-scss-orphan`; landed together)
  - *Problem:* corpus/tech-blog/theme.scss (218 lines) is a Quarto `darkly`-based SCSS override sheet ('Loaded via: theme: [darkly, theme.scss]', L2). Taliesin uses CSS custom properties, never SCSS, and _site.yml has no `theme:` key referencing it (only `css: custom.css`). No .tmd references it. It is pure dead weight that confuses the source tree and invites edits that will never take effect (a maintainer could 'fix' a color here and see nothing change).
  - *Fix:* Delete corpus/tech-blog/theme.scss. If any of its typography intent (Inter body, JetBrains Mono, 1.75 line-height, no-accent tonal palette) is desired, it must instead be expressed via Taliesin's `--tali-*` CSS variables / theme system, not SCSS. Verify the blog's current fonts/colors come from the native theme before deleting so nothing visual is lost (it won't be — the SCSS is not loaded).

- [x] `#rss-feed-silently-dropped` **Footer advertises an RSS feed the engine silently drops and never generates** — `P2` [content+framework] `L` `Q` ↓
  - *Problem:* F4 needs correcting: the RSS link does not 404 — chrome.rs:185-192 explicitly detects a local `.xml` href and `continue`s past it ('this build generates no RSS feed'), so the configured RSS footer item (_site.yml L47-48, href:/blog.xml) simply VANISHES from the rendered footer (built home shows only LinkedIn + GitHub, no RSS icon). That is arguably worse than a 404: the author configured a feed, sees the icon disappear with no warning, and no feed is ever produced. The engine has no RSS/feed/Atom generation at all (grep: the only `feed.tmd` reference in mod.rs:1718 is unrelated listing scaffolding). For a career-facing blog whose whole point is publishing posts, a discoverable feed is a real gap.
  - *Fix:* FRAMEWORK (the real fix, ties to 'perfect the default'): auto-generate a feed from any `listing:` over a posts directory that has dates — emit blog.xml (Atom/RSS) during site build, using the site url:/title:/description: already in config, and stop silently dropping the .xml footer link once the file exists. This makes every Taliesin blog get a working feed with zero config. SHORT-TERM content-config: until generation lands, remove the RSS item (L47-48) from _site.yml so the config doesn't advertise a feed that doesn't exist. Do not leave the silent-drop behavior as the permanent answer — at minimum the engine should warn 'configured RSS link /blog.xml dropped: no feed generated'.

- [x] `#footer-icon-shorthand` **Footer hand-rolls raw social SVG blobs the engine already provides via icon:** — `P2` [content] `S` `Q`
  - *Problem:* _site.yml footer.right (L43-48) pastes full inline <svg> path blobs + <span class='sr-only'> for LinkedIn, GitHub, and RSS — the exact three glyphs chrome.rs's social_icon() already bundles (L378-388, github/linkedin/rss cases). The raw-SVG approach is verbose, un-maintainable, is the sole reason custom.css's .sr-only must survive, and (per the chrome.rs footer path L173-178) produces a link with no aria-label because the SVG-as-text branch is taken instead of the icon branch. It is Quarto-era hand-authoring of something Taliesin made a first-class shorthand.
  - *Fix:* Replace each footer item with the native shorthand: `- { icon: github, href: ... }`, `- { icon: linkedin, href: ... }`. This emits the bundled SVG with a proper aria-label (chrome.rs:173-177), removes ~3 lines of SVG blob per item, and eliminates the .sr-only dependency so custom.css can be deleted outright. Drop the RSS item entirely until feed generation exists (see rss finding).

- [x] `#no-sitemap-robots` **Site build emits no sitemap.xml or robots.txt despite a configured url:** — `P2` [framework] `M`
  - *Problem:* The build output contains no sitemap.xml and no robots.txt (ls of build/tech-blog shows neither). meta.rs already computes clean per-page canonical URLs from cfg.url (meta.rs:22-25) and the discovery walk already enumerates every page, so a sitemap is nearly free — yet none is produced. For a career-facing blog whose goal is being found by recruiters/peers, a sitemap materially helps indexing, and its absence is a silent SEO gap on every Taliesin site that sets url:.
  - *Fix:* FRAMEWORK ('perfect the default'): when _site.yml has `url:`, auto-emit sitemap.xml (loop the same non-draft Page list meta.rs already has canonical URLs for) and a minimal robots.txt pointing at it, during `build`. No knob needed — url: presence is the trigger. This benefits every Taliesin site with zero config and removes a reason to hand-write head:/extra files.

- [ ] `#quarto-value-noop-lint` **Quarto-specific frontmatter VALUES are silently ignored (template: jolla, page-layout: article)** — `P2` [content+framework] `M` `Q`
  - *Problem:* Taliesin adopted the Quarto frontmatter KEYS (about/template, page-layout, listing/type, title-block-style all in KNOWN_KEYS), so the validator never warns on them — good adoption. But several VALUES are Quarto-isms that Taliesin ignores: `about.template: jolla` (index.tmd:4) is only stashed as a CSS class `tali-about-{tpl}` (frontmatter.rs:107, mod.rs:70-71); the layout is always the fixed jolla style regardless of value, so 'jolla' happens to work by coincidence and any other Quarto template name (trestles/marquee/solana) would silently produce a meaningless class. `page-layout: article` (index.tmd:7) is a no-op — only `full` does anything (page.rs:39, mod.rs:481). A maintainer de-Quarto-ing gets no signal that these values are inert.
  - *Fix:* Content-config: in the blog, since only jolla exists, either drop `template:` entirely (it defaults to jolla anyway, frontmatter.rs:107) or keep it, and drop `page-layout: article` (it's the default). FRAMEWORK ('perfect the default' + explicit rejection): extend the front-matter validator to check the closed-set VALUES it already knows — warn on an about template that isn't the one Taliesin renders, and on page-layout values other than the supported ones — so ignored Quarto idioms surface as a warning instead of coincidentally-working dead config. This is the natural home for a lightweight 'from-quarto' lint.

- [x] `#jsonld-structured-data` **No JSON-LD structured data (schema.org Person / BlogPosting)** — `P3` [framework] `M`
  - *Problem:* meta.rs emits OG/Twitter/citation meta but no schema.org JSON-LD. For a personal brand blog, a Person node (name, sameAs: the GitHub/LinkedIn already in the footer) on the home/about and a BlogPosting node (headline, datePublished, author) on posts is what lets Google build a knowledge-panel-style rich result and reliably attribute posts to Andreas. All the inputs already exist in config + front matter.
  - *Fix:* FRAMEWORK, low-priority: optionally emit a JSON-LD <script type=application/ld+json> alongside the existing meta — Person on about/home (sameAs from footer social links), BlogPosting on any page with a date+author (reusing the same fields meta.rs already gathers at :93-109). Keep it opt-out-free and derived, no new knob. Lower priority than feed/sitemap; list it as a nice-to-have.

- [KEEP] `#keep-meta-and-validator-architecture` **KEEP: native OG/Twitter/citation head + the vocab/validator drift-lock** — `keep` [framework] `S`
  - *Problem:* Two existing decisions are genuinely strong native design and must not be lost in the de-Quarto sweep. (1) meta.rs builds a complete, correct social/SEO head — description, og:type (article vs website by date presence), og:title/description/site_name/url, absolute og:image, twitter card sized by image presence, canonical link, and Google Scholar citation_* meta gated on date+author (meta.rs:17-111). This is exactly the right default for a scholarly career blog and is fully native/offline. (2) The frontmatter validator + vocab.rs are golden-file drift-locked to the SAME consts `check` enforces (vocab.rs:216-243, test at :260), so autocomplete can never drift from validation — an excellent maintainability invariant.
  - *Fix:* Do not touch meta.rs's generation or the vocab/validator coupling. When adding the feed/sitemap/JSON-LD framework work, reuse meta.rs's existing canonical-URL and image-absolutization logic rather than recomputing. Treat the vocab drift-lock as the model for any new closed-set (e.g. the value-lint above should add its allowed values to the same const-sourced path).


---

## KEEP list — protect these (14)

Good decisions the audit validated; do not "fix" them.

- `#keep-page-layout-and-title-block-style` — KEEP: page-layout: and title-block-style: none are Quarto idioms Taliesin deliberately implemented and honors
- `#serif-body-sans-head-pairing` — Serif body + sans headings is the native default and a genuinely distinctive editorial voice — keep it
- `#keep-live-figure-thumbnails` — KEEP + amplify: the live-generated math figures as post thumbnails are the real brand
- `#keep-blog-and-cv-voice` — KEEP: the /blog and /cv opening lines are the authentic voice, promote them
- `#projects-listing-and-framing-are-good` — Projects listing (visual cards + honest 'things I built to learn' framing) should stay
- `#keep-post-descriptions-voice` — KEEP: most post/project descriptions and the blog/projects taglines are genuinely strong
- `#keep-real-contrast-and-focus-foundation` — KEEP: muted-text contrast meets AA in both themes and the skip/focus/reduced-motion foundation is solid
- `#offline-first-verified` — Zero-CDN promise holds: no external request on any page, both sites
- `#lcp-profile-webp-good` — LCP handling of the home profile image is correctly tuned
- `#conditional-heavy-lib-loading-good` — d3/Plot load only where used; mermaid runtime ships on zero pages
- `#per-post-og-canonical-good` — KEEP: per-post unique description, canonical directory URL, og:type=article and per-post card image
- `#no-overflow-baseline` — Zero page-level horizontal overflow; overflow is correctly contained in scroll blocks
- `#nav-burger-implementation` — Mobile nav collapse is a solid, WCAG-sized implementation
- `#keep-meta-and-validator-architecture` — KEEP: native OG/Twitter/citation head + the vocab/validator drift-lock
