[package]
name = "qmd-fast-core"
description = "Parser, block model, and HTML rendering for qmd-fast"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
comrak = "0.52.0"
katex = "0.4.6"
serde = { workspace = true }
serde_yaml = { workspace = true }
syntect = { workspace = true }
